package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameEnviados generated by hbm2java
 */
public class MdlAlertameEnviados  implements java.io.Serializable {


     private Long id;
     private Long eventoid;
     private Long userid;
     private String mensagem;
     private Long transmitido;
     private Long horario;
     private String tipo;

    public MdlAlertameEnviados() {
    }

    public MdlAlertameEnviados(Long eventoid, Long userid, String mensagem, Long transmitido, Long horario, String tipo) {
       this.eventoid = eventoid;
       this.userid = userid;
       this.mensagem = mensagem;
       this.transmitido = transmitido;
       this.horario = horario;
       this.tipo = tipo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getEventoid() {
        return this.eventoid;
    }
    
    public void setEventoid(Long eventoid) {
        this.eventoid = eventoid;
    }
    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public Long getTransmitido() {
        return this.transmitido;
    }
    
    public void setTransmitido(Long transmitido) {
        this.transmitido = transmitido;
    }
    public Long getHorario() {
        return this.horario;
    }
    
    public void setHorario(Long horario) {
        this.horario = horario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


