package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameInteresses generated by hbm2java
 */
public class MdlAlertameInteresses  implements java.io.Serializable {


     private Long id;
     private Long userid;
     private Long alertameid;
     private Long course;
     private Long notificacaoid;
     private Long inicio;

    public MdlAlertameInteresses() {
    }

    public MdlAlertameInteresses(Long userid, Long alertameid, Long course, Long notificacaoid, Long inicio) {
       this.userid = userid;
       this.alertameid = alertameid;
       this.course = course;
       this.notificacaoid = notificacaoid;
       this.inicio = inicio;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }
    public Long getAlertameid() {
        return this.alertameid;
    }
    
    public void setAlertameid(Long alertameid) {
        this.alertameid = alertameid;
    }
    public Long getCourse() {
        return this.course;
    }
    
    public void setCourse(Long course) {
        this.course = course;
    }
    public Long getNotificacaoid() {
        return this.notificacaoid;
    }
    
    public void setNotificacaoid(Long notificacaoid) {
        this.notificacaoid = notificacaoid;
    }
    public Long getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Long inicio) {
        this.inicio = inicio;
    }




}


