package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameEncerramento generated by hbm2java
 */
public class MdlAlertameEncerramento  implements java.io.Serializable {


     private Long id;
     private Long atividade;
     private Long notificacaoid;

    public MdlAlertameEncerramento() {
    }

    public MdlAlertameEncerramento(Long atividade, Long notificacaoid) {
       this.atividade = atividade;
       this.notificacaoid = notificacaoid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(Long atividade) {
        this.atividade = atividade;
    }
    public Long getNotificacaoid() {
        return this.notificacaoid;
    }
    
    public void setNotificacaoid(Long notificacaoid) {
        this.notificacaoid = notificacaoid;
    }




}


