package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameCategoria generated by hbm2java
 */
public class MdlAlertameCategoria  implements java.io.Serializable {


     private Long id;
     private String categoria;

    public MdlAlertameCategoria() {
    }

    public MdlAlertameCategoria(String categoria) {
       this.categoria = categoria;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }




}


