package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameNotificacao generated by hbm2java
 */
public class MdlAlertameNotificacao  implements java.io.Serializable {


     private Long id;
     private String descricao;
     private Long roleid;
     private Long categoriaid;
     private String tipo;

    public MdlAlertameNotificacao() {
    }

    public MdlAlertameNotificacao(String descricao, Long roleid, Long categoriaid, String tipo) {
       this.descricao = descricao;
       this.roleid = roleid;
       this.categoriaid = categoriaid;
       this.tipo = tipo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
    public Long getCategoriaid() {
        return this.categoriaid;
    }
    
    public void setCategoriaid(Long categoriaid) {
        this.categoriaid = categoriaid;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


