package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameEventos generated by hbm2java
 */
public class MdlAlertameEventos  implements java.io.Serializable {


     private Long id;
     private Long logid;
     private Long notificacaoid;
     private Boolean viewed;
     private Long criacao;

    public MdlAlertameEventos() {
    }

    public MdlAlertameEventos(Long logid, Long notificacaoid, Boolean viewed, Long criacao) {
       this.logid = logid;
       this.notificacaoid = notificacaoid;
       this.viewed = viewed;
       this.criacao = criacao;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getLogid() {
        return this.logid;
    }
    
    public void setLogid(Long logid) {
        this.logid = logid;
    }
    public Long getNotificacaoid() {
        return this.notificacaoid;
    }
    
    public void setNotificacaoid(Long notificacaoid) {
        this.notificacaoid = notificacaoid;
    }
    public Boolean getViewed() {
        return this.viewed;
    }
    
    public void setViewed(Boolean viewed) {
        this.viewed = viewed;
    }
    public Long getCriacao() {
        return this.criacao;
    }
    
    public void setCriacao(Long criacao) {
        this.criacao = criacao;
    }

    @Override
    public String toString() {
        return "MdlAlertameEventos{" + "id=" + id + ", logid=" + logid + ", notificacaoid=" + notificacaoid + ", viewed=" + viewed + ", criacao=" + criacao + '}';
    }

}


