package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAssignmentSubmissions generated by hbm2java
 */
public class MdlAssignmentSubmissions  implements java.io.Serializable {


     private Long id;
     private long assignment;
     private long userid;
     private long timecreated;
     private long timemodified;
     private long numfiles;
     private String data1;
     private String data2;
     private long grade;
     private String submissioncomment;
     private short format;
     private long teacher;
     private long timemarked;
     private boolean mailed;

    public MdlAssignmentSubmissions() {
    }

	
    public MdlAssignmentSubmissions(long assignment, long userid, long timecreated, long timemodified, long numfiles, long grade, String submissioncomment, short format, long teacher, long timemarked, boolean mailed) {
        this.assignment = assignment;
        this.userid = userid;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
        this.numfiles = numfiles;
        this.grade = grade;
        this.submissioncomment = submissioncomment;
        this.format = format;
        this.teacher = teacher;
        this.timemarked = timemarked;
        this.mailed = mailed;
    }
    public MdlAssignmentSubmissions(long assignment, long userid, long timecreated, long timemodified, long numfiles, String data1, String data2, long grade, String submissioncomment, short format, long teacher, long timemarked, boolean mailed) {
       this.assignment = assignment;
       this.userid = userid;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.numfiles = numfiles;
       this.data1 = data1;
       this.data2 = data2;
       this.grade = grade;
       this.submissioncomment = submissioncomment;
       this.format = format;
       this.teacher = teacher;
       this.timemarked = timemarked;
       this.mailed = mailed;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(long assignment) {
        this.assignment = assignment;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public long getNumfiles() {
        return this.numfiles;
    }
    
    public void setNumfiles(long numfiles) {
        this.numfiles = numfiles;
    }
    public String getData1() {
        return this.data1;
    }
    
    public void setData1(String data1) {
        this.data1 = data1;
    }
    public String getData2() {
        return this.data2;
    }
    
    public void setData2(String data2) {
        this.data2 = data2;
    }
    public long getGrade() {
        return this.grade;
    }
    
    public void setGrade(long grade) {
        this.grade = grade;
    }
    public String getSubmissioncomment() {
        return this.submissioncomment;
    }
    
    public void setSubmissioncomment(String submissioncomment) {
        this.submissioncomment = submissioncomment;
    }
    public short getFormat() {
        return this.format;
    }
    
    public void setFormat(short format) {
        this.format = format;
    }
    public long getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(long teacher) {
        this.teacher = teacher;
    }
    public long getTimemarked() {
        return this.timemarked;
    }
    
    public void setTimemarked(long timemarked) {
        this.timemarked = timemarked;
    }
    public boolean isMailed() {
        return this.mailed;
    }
    
    public void setMailed(boolean mailed) {
        this.mailed = mailed;
    }




}


