package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertameAtividades generated by hbm2java
 */
public class MdlAlertameAtividades  implements java.io.Serializable {


     private Long id;
     private String nome;
     private long curso;
     private long instancia;
     private long modulo;
     private String tipo;
     private Long criacao;
     private Long edicao;
     private Long encerramento;
     private Long cmid;
     private Long logid;
     private Long versao;
     private boolean visivel;

    public MdlAlertameAtividades() {
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public long getCurso() {
        return this.curso;
    }
    
    public void setCurso(long curso) {
        this.curso = curso;
    }
    public long getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(long instancia) {
        this.instancia = instancia;
    }
    public long getModulo() {
        return this.modulo;
    }
    
    public void setModulo(long modulo) {
        this.modulo = modulo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Long getCriacao() {
        return this.criacao;
    }
    
    public void setCriacao(Long criacao) {
        this.criacao = criacao;
    }
    public Long getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(Long edicao) {
        this.edicao = edicao;
    }
    
    public Long getEncerramento() {
        return this.encerramento;
    }
    
    public void setEncerramento(Long encerramento) {
        this.encerramento = encerramento;
    }
    public Long getCmid() {
        return this.cmid;
    }
    
    public void setCmid(Long cmid) {
        this.cmid = cmid;
    }
    public Long getLogid() {
        return this.logid;
    }
    
    public void setLogid(Long logid) {
        this.logid = logid;
    }
    public Long getVersao() {
        return this.versao;
    }
    
    public void setVersao(Long versao) {
        this.versao = versao;
    }
    public boolean isVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(boolean visto) {
        this.visivel = visto;
    }

    @Override
    public String toString() {
        return "MdlAlertameAtividades{" + "id=" + id + ", nome=" + nome + ", curso=" + curso + ", instancia=" + instancia + ", modulo=" + modulo + ", tipo=" + tipo + ", criacao=" + criacao + ", edicao=" + edicao + ", encerramento=" + encerramento + ", cmid=" + cmid + ", logid=" + logid + ", versao=" + versao + ", visivel=" + visivel + '}';
    }
    
}


