package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAlertame generated by hbm2java
 */
public class MdlAlertame  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String intro;
     private long introformat;
     private long timecreated;
     private long timemodified;

    public MdlAlertame() {
    }

	
    public MdlAlertame(long course, String name, long introformat, long timecreated, long timemodified) {
        this.course = course;
        this.name = name;
        this.introformat = introformat;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
    }
    public MdlAlertame(long course, String name, String intro, long introformat, long timecreated, long timemodified) {
       this.course = course;
       this.name = name;
       this.intro = intro;
       this.introformat = introformat;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public long getIntroformat() {
        return this.introformat;
    }
    
    public void setIntroformat(long introformat) {
        this.introformat = introformat;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


