package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlAssignment generated by hbm2java
 */
public class MdlAssignment  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String description;
     private short format;
     private String assignmenttype;
     private byte resubmit;
     private byte preventlate;
     private byte emailteachers;
     private Long var1;
     private Long var2;
     private Long var3;
     private Long var4;
     private Long var5;
     private long maxbytes;
     private long timedue;
     private long timeavailable;
     private long grade;
     private long timemodified;

    public MdlAssignment() {
    }

	
    public MdlAssignment(long course, String name, String description, short format, String assignmenttype, byte resubmit, byte preventlate, byte emailteachers, long maxbytes, long timedue, long timeavailable, long grade, long timemodified) {
        this.course = course;
        this.name = name;
        this.description = description;
        this.format = format;
        this.assignmenttype = assignmenttype;
        this.resubmit = resubmit;
        this.preventlate = preventlate;
        this.emailteachers = emailteachers;
        this.maxbytes = maxbytes;
        this.timedue = timedue;
        this.timeavailable = timeavailable;
        this.grade = grade;
        this.timemodified = timemodified;
    }
    public MdlAssignment(long course, String name, String description, short format, String assignmenttype, byte resubmit, byte preventlate, byte emailteachers, Long var1, Long var2, Long var3, Long var4, Long var5, long maxbytes, long timedue, long timeavailable, long grade, long timemodified) {
       this.course = course;
       this.name = name;
       this.description = description;
       this.format = format;
       this.assignmenttype = assignmenttype;
       this.resubmit = resubmit;
       this.preventlate = preventlate;
       this.emailteachers = emailteachers;
       this.var1 = var1;
       this.var2 = var2;
       this.var3 = var3;
       this.var4 = var4;
       this.var5 = var5;
       this.maxbytes = maxbytes;
       this.timedue = timedue;
       this.timeavailable = timeavailable;
       this.grade = grade;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public short getFormat() {
        return this.format;
    }
    
    public void setFormat(short format) {
        this.format = format;
    }
    public String getAssignmenttype() {
        return this.assignmenttype;
    }
    
    public void setAssignmenttype(String assignmenttype) {
        this.assignmenttype = assignmenttype;
    }
    public byte getResubmit() {
        return this.resubmit;
    }
    
    public void setResubmit(byte resubmit) {
        this.resubmit = resubmit;
    }
    public byte getPreventlate() {
        return this.preventlate;
    }
    
    public void setPreventlate(byte preventlate) {
        this.preventlate = preventlate;
    }
    public byte getEmailteachers() {
        return this.emailteachers;
    }
    
    public void setEmailteachers(byte emailteachers) {
        this.emailteachers = emailteachers;
    }
    public Long getVar1() {
        return this.var1;
    }
    
    public void setVar1(Long var1) {
        this.var1 = var1;
    }
    public Long getVar2() {
        return this.var2;
    }
    
    public void setVar2(Long var2) {
        this.var2 = var2;
    }
    public Long getVar3() {
        return this.var3;
    }
    
    public void setVar3(Long var3) {
        this.var3 = var3;
    }
    public Long getVar4() {
        return this.var4;
    }
    
    public void setVar4(Long var4) {
        this.var4 = var4;
    }
    public Long getVar5() {
        return this.var5;
    }
    
    public void setVar5(Long var5) {
        this.var5 = var5;
    }
    public long getMaxbytes() {
        return this.maxbytes;
    }
    
    public void setMaxbytes(long maxbytes) {
        this.maxbytes = maxbytes;
    }
    public long getTimedue() {
        return this.timedue;
    }
    
    public void setTimedue(long timedue) {
        this.timedue = timedue;
    }
    public long getTimeavailable() {
        return this.timeavailable;
    }
    
    public void setTimeavailable(long timeavailable) {
        this.timeavailable = timeavailable;
    }
    public long getGrade() {
        return this.grade;
    }
    
    public void setGrade(long grade) {
        this.grade = grade;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


