package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlBackupIds generated by hbm2java
 */
public class MdlBackupIds  implements java.io.Serializable {


     private Long id;
     private long backupCode;
     private String tableName;
     private long oldId;
     private long newId;
     private String info;

    public MdlBackupIds() {
    }

    public MdlBackupIds(long backupCode, String tableName, long oldId, long newId, String info) {
       this.backupCode = backupCode;
       this.tableName = tableName;
       this.oldId = oldId;
       this.newId = newId;
       this.info = info;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getBackupCode() {
        return this.backupCode;
    }
    
    public void setBackupCode(long backupCode) {
        this.backupCode = backupCode;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public long getOldId() {
        return this.oldId;
    }
    
    public void setOldId(long oldId) {
        this.oldId = oldId;
    }
    public long getNewId() {
        return this.newId;
    }
    
    public void setNewId(long newId) {
        this.newId = newId;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


