package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlBlock generated by hbm2java
 */
public class MdlBlock  implements java.io.Serializable {


     private Long id;
     private long version;
     private String name;
     private long cron;
     private long lastcron;
     private boolean visible;
     private boolean multiple;

    public MdlBlock() {
    }

    public MdlBlock(String name, long cron, long lastcron, boolean visible, boolean multiple) {
       this.name = name;
       this.cron = cron;
       this.lastcron = lastcron;
       this.visible = visible;
       this.multiple = multiple;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getCron() {
        return this.cron;
    }
    
    public void setCron(long cron) {
        this.cron = cron;
    }
    public long getLastcron() {
        return this.lastcron;
    }
    
    public void setLastcron(long lastcron) {
        this.lastcron = lastcron;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public boolean isMultiple() {
        return this.multiple;
    }
    
    public void setMultiple(boolean multiple) {
        this.multiple = multiple;
    }




}


