package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlBlockInstance generated by hbm2java
 */
public class MdlBlockInstance  implements java.io.Serializable {


     private Long id;
     private long blockid;
     private long pageid;
     private String pagetype;
     private String position;
     private short weight;
     private boolean visible;
     private String configdata;

    public MdlBlockInstance() {
    }

	
    public MdlBlockInstance(long blockid, long pageid, String pagetype, String position, short weight, boolean visible) {
        this.blockid = blockid;
        this.pageid = pageid;
        this.pagetype = pagetype;
        this.position = position;
        this.weight = weight;
        this.visible = visible;
    }
    public MdlBlockInstance(long blockid, long pageid, String pagetype, String position, short weight, boolean visible, String configdata) {
       this.blockid = blockid;
       this.pageid = pageid;
       this.pagetype = pagetype;
       this.position = position;
       this.weight = weight;
       this.visible = visible;
       this.configdata = configdata;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getBlockid() {
        return this.blockid;
    }
    
    public void setBlockid(long blockid) {
        this.blockid = blockid;
    }
    public long getPageid() {
        return this.pageid;
    }
    
    public void setPageid(long pageid) {
        this.pageid = pageid;
    }
    public String getPagetype() {
        return this.pagetype;
    }
    
    public void setPagetype(String pagetype) {
        this.pagetype = pagetype;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public short getWeight() {
        return this.weight;
    }
    
    public void setWeight(short weight) {
        this.weight = weight;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public String getConfigdata() {
        return this.configdata;
    }
    
    public void setConfigdata(String configdata) {
        this.configdata = configdata;
    }




}


