package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlBackupLog generated by hbm2java
 */
public class MdlBackupLog  implements java.io.Serializable {


     private Long id;
     private long courseid;
     private long time;
     private long laststarttime;
     private String info;

    public MdlBackupLog() {
    }

    public MdlBackupLog(long courseid, long time, long laststarttime, String info) {
       this.courseid = courseid;
       this.time = time;
       this.laststarttime = laststarttime;
       this.info = info;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public long getLaststarttime() {
        return this.laststarttime;
    }
    
    public void setLaststarttime(long laststarttime) {
        this.laststarttime = laststarttime;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


