package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseSections generated by hbm2java
 */
public class MdlCourseSections  implements java.io.Serializable {


     private Long id;
     private long course;
     private long section;
     private String summary;
     private String sequence;
     private boolean visible;

    public MdlCourseSections() {
    }

	
    public MdlCourseSections(long course, long section, boolean visible) {
        this.course = course;
        this.section = section;
        this.visible = visible;
    }
    public MdlCourseSections(long course, long section, String summary, String sequence, boolean visible) {
       this.course = course;
       this.section = section;
       this.summary = summary;
       this.sequence = sequence;
       this.visible = visible;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getSection() {
        return this.section;
    }
    
    public void setSection(long section) {
        this.section = section;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getSequence() {
        return this.sequence;
    }
    
    public void setSequence(String sequence) {
        this.sequence = sequence;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }




}


