package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseDisplay generated by hbm2java
 */
public class MdlCourseDisplay  implements java.io.Serializable {


     private Long id;
     private long course;
     private long userid;
     private long display;

    public MdlCourseDisplay() {
    }

    public MdlCourseDisplay(long course, long userid, long display) {
       this.course = course;
       this.userid = userid;
       this.display = display;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getDisplay() {
        return this.display;
    }
    
    public void setDisplay(long display) {
        this.display = display;
    }




}


