package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseMeta generated by hbm2java
 */
public class MdlCourseMeta  implements java.io.Serializable {


     private Long id;
     private long parentCourse;
     private long childCourse;

    public MdlCourseMeta() {
    }

    public MdlCourseMeta(long parentCourse, long childCourse) {
       this.parentCourse = parentCourse;
       this.childCourse = childCourse;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getParentCourse() {
        return this.parentCourse;
    }
    
    public void setParentCourse(long parentCourse) {
        this.parentCourse = parentCourse;
    }
    public long getChildCourse() {
        return this.childCourse;
    }
    
    public void setChildCourse(long childCourse) {
        this.childCourse = childCourse;
    }




}


