package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlChoiceOptions generated by hbm2java
 */
public class MdlChoiceOptions  implements java.io.Serializable {


     private Long id;
     private long choiceid;
     private String text;
     private Long maxanswers;
     private long timemodified;

    public MdlChoiceOptions() {
    }

	
    public MdlChoiceOptions(long choiceid, long timemodified) {
        this.choiceid = choiceid;
        this.timemodified = timemodified;
    }
    public MdlChoiceOptions(long choiceid, String text, Long maxanswers, long timemodified) {
       this.choiceid = choiceid;
       this.text = text;
       this.maxanswers = maxanswers;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getChoiceid() {
        return this.choiceid;
    }
    
    public void setChoiceid(long choiceid) {
        this.choiceid = choiceid;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Long getMaxanswers() {
        return this.maxanswers;
    }
    
    public void setMaxanswers(Long maxanswers) {
        this.maxanswers = maxanswers;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


