package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseRequest generated by hbm2java
 */
public class MdlCourseRequest  implements java.io.Serializable {


     private Long id;
     private String fullname;
     private String shortname;
     private String summary;
     private String reason;
     private long requester;
     private String password;

    public MdlCourseRequest() {
    }

    public MdlCourseRequest(String fullname, String shortname, String summary, String reason, long requester, String password) {
       this.fullname = fullname;
       this.shortname = shortname;
       this.summary = summary;
       this.reason = reason;
       this.requester = requester;
       this.password = password;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public long getRequester() {
        return this.requester;
    }
    
    public void setRequester(long requester) {
        this.requester = requester;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


