package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseCategories generated by hbm2java
 */
public class MdlCourseCategories  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private long parent;
     private long sortorder;
     private long coursecount;
     private boolean visible;
     private long timemodified;
     private long depth;
     private String path;
     private String theme;

    public MdlCourseCategories() {
    }

	
    public MdlCourseCategories(String name, long parent, long sortorder, long coursecount, boolean visible, long timemodified, long depth, String path) {
        this.name = name;
        this.parent = parent;
        this.sortorder = sortorder;
        this.coursecount = coursecount;
        this.visible = visible;
        this.timemodified = timemodified;
        this.depth = depth;
        this.path = path;
    }
    public MdlCourseCategories(String name, String description, long parent, long sortorder, long coursecount, boolean visible, long timemodified, long depth, String path, String theme) {
       this.name = name;
       this.description = description;
       this.parent = parent;
       this.sortorder = sortorder;
       this.coursecount = coursecount;
       this.visible = visible;
       this.timemodified = timemodified;
       this.depth = depth;
       this.path = path;
       this.theme = theme;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getParent() {
        return this.parent;
    }
    
    public void setParent(long parent) {
        this.parent = parent;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }
    public long getCoursecount() {
        return this.coursecount;
    }
    
    public void setCoursecount(long coursecount) {
        this.coursecount = coursecount;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public long getDepth() {
        return this.depth;
    }
    
    public void setDepth(long depth) {
        this.depth = depth;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }




}


