package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlChoice generated by hbm2java
 */
public class MdlChoice  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String text;
     private byte format;
     private byte publish;
     private byte showresults;
     private short display;
     private byte allowupdate;
     private byte showunanswered;
     private byte limitanswers;
     private long timeopen;
     private long timeclose;
     private long timemodified;

    public MdlChoice() {
    }

    public MdlChoice(long course, String name, String text, byte format, byte publish, byte showresults, short display, byte allowupdate, byte showunanswered, byte limitanswers, long timeopen, long timeclose, long timemodified) {
       this.course = course;
       this.name = name;
       this.text = text;
       this.format = format;
       this.publish = publish;
       this.showresults = showresults;
       this.display = display;
       this.allowupdate = allowupdate;
       this.showunanswered = showunanswered;
       this.limitanswers = limitanswers;
       this.timeopen = timeopen;
       this.timeclose = timeclose;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public byte getFormat() {
        return this.format;
    }
    
    public void setFormat(byte format) {
        this.format = format;
    }
    public byte getPublish() {
        return this.publish;
    }
    
    public void setPublish(byte publish) {
        this.publish = publish;
    }
    public byte getShowresults() {
        return this.showresults;
    }
    
    public void setShowresults(byte showresults) {
        this.showresults = showresults;
    }
    public short getDisplay() {
        return this.display;
    }
    
    public void setDisplay(short display) {
        this.display = display;
    }
    public byte getAllowupdate() {
        return this.allowupdate;
    }
    
    public void setAllowupdate(byte allowupdate) {
        this.allowupdate = allowupdate;
    }
    public byte getShowunanswered() {
        return this.showunanswered;
    }
    
    public void setShowunanswered(byte showunanswered) {
        this.showunanswered = showunanswered;
    }
    public byte getLimitanswers() {
        return this.limitanswers;
    }
    
    public void setLimitanswers(byte limitanswers) {
        this.limitanswers = limitanswers;
    }
    public long getTimeopen() {
        return this.timeopen;
    }
    
    public void setTimeopen(long timeopen) {
        this.timeopen = timeopen;
    }
    public long getTimeclose() {
        return this.timeclose;
    }
    
    public void setTimeclose(long timeclose) {
        this.timeclose = timeclose;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


