package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCacheText generated by hbm2java
 */
public class MdlCacheText  implements java.io.Serializable {


     private Long id;
     private String md5key;
     private String formattedtext;
     private long timemodified;

    public MdlCacheText() {
    }

    public MdlCacheText(String md5key, String formattedtext, long timemodified) {
       this.md5key = md5key;
       this.formattedtext = formattedtext;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getMd5key() {
        return this.md5key;
    }
    
    public void setMd5key(String md5key) {
        this.md5key = md5key;
    }
    public String getFormattedtext() {
        return this.formattedtext;
    }
    
    public void setFormattedtext(String formattedtext) {
        this.formattedtext = formattedtext;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


