package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCourseAllowedModules generated by hbm2java
 */
public class MdlCourseAllowedModules  implements java.io.Serializable {


     private Long id;
     private long course;
     private long module;

    public MdlCourseAllowedModules() {
    }

    public MdlCourseAllowedModules(long course, long module) {
       this.course = course;
       this.module = module;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getModule() {
        return this.module;
    }
    
    public void setModule(long module) {
        this.module = module;
    }




}


