package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlCacheFilters generated by hbm2java
 */
public class MdlCacheFilters  implements java.io.Serializable {


     private Long id;
     private long version;
     private String filter;
     private String md5key;
     private String rawtext;
     private long timemodified;

    public MdlCacheFilters() {
    }

    public MdlCacheFilters(String filter, String md5key, String rawtext, long timemodified) {
       this.filter = filter;
       this.md5key = md5key;
       this.rawtext = rawtext;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getFilter() {
        return this.filter;
    }
    
    public void setFilter(String filter) {
        this.filter = filter;
    }
    public String getMd5key() {
        return this.md5key;
    }
    
    public void setMd5key(String md5key) {
        this.md5key = md5key;
    }
    public String getRawtext() {
        return this.rawtext;
    }
    
    public void setRawtext(String rawtext) {
        this.rawtext = rawtext;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


