package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlChatUsers generated by hbm2java
 */
public class MdlChatUsers  implements java.io.Serializable {


     private Long id;
     private String version;
     private long chatid;
     private long userid;
     private long groupid;
     private String ip;
     private long firstping;
     private long lastping;
     private long lastmessageping;
     private String sid;
     private long course;
     private String lang;

    public MdlChatUsers() {
    }

    public MdlChatUsers(long chatid, long userid, long groupid, String ip, long firstping, long lastping, long lastmessageping, String sid, long course, String lang) {
       this.chatid = chatid;
       this.userid = userid;
       this.groupid = groupid;
       this.ip = ip;
       this.firstping = firstping;
       this.lastping = lastping;
       this.lastmessageping = lastmessageping;
       this.sid = sid;
       this.course = course;
       this.lang = lang;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public long getChatid() {
        return this.chatid;
    }
    
    public void setChatid(long chatid) {
        this.chatid = chatid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public long getFirstping() {
        return this.firstping;
    }
    
    public void setFirstping(long firstping) {
        this.firstping = firstping;
    }
    public long getLastping() {
        return this.lastping;
    }
    
    public void setLastping(long lastping) {
        this.lastping = lastping;
    }
    public long getLastmessageping() {
        return this.lastmessageping;
    }
    
    public void setLastmessageping(long lastmessageping) {
        this.lastmessageping = lastmessageping;
    }
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


