package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlConfigPlugins generated by hbm2java
 */
public class MdlConfigPlugins  implements java.io.Serializable {


     private Long id;
     private String plugin;
     private String name;
     private String value;

    public MdlConfigPlugins() {
    }

    public MdlConfigPlugins(String plugin, String name, String value) {
       this.plugin = plugin;
       this.name = name;
       this.value = value;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPlugin() {
        return this.plugin;
    }
    
    public void setPlugin(String plugin) {
        this.plugin = plugin;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


