package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlDataRatings generated by hbm2java
 */
public class MdlDataRatings  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long recordid;
     private long rating;

    public MdlDataRatings() {
    }

    public MdlDataRatings(long userid, long recordid, long rating) {
       this.userid = userid;
       this.recordid = recordid;
       this.rating = rating;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getRecordid() {
        return this.recordid;
    }
    
    public void setRecordid(long recordid) {
        this.recordid = recordid;
    }
    public long getRating() {
        return this.rating;
    }
    
    public void setRating(long rating) {
        this.rating = rating;
    }




}


