package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlDataRecords generated by hbm2java
 */
public class MdlDataRecords  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long groupid;
     private long dataid;
     private long timecreated;
     private long timemodified;
     private short approved;

    public MdlDataRecords() {
    }

    public MdlDataRecords(long userid, long groupid, long dataid, long timecreated, long timemodified, short approved) {
       this.userid = userid;
       this.groupid = groupid;
       this.dataid = dataid;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.approved = approved;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getDataid() {
        return this.dataid;
    }
    
    public void setDataid(long dataid) {
        this.dataid = dataid;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public short getApproved() {
        return this.approved;
    }
    
    public void setApproved(short approved) {
        this.approved = approved;
    }




}


