package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEventsHandlers generated by hbm2java
 */
public class MdlEventsHandlers  implements java.io.Serializable {


     private Long id;
     private String eventname;
     private String handlermodule;
     private String handlerfile;
     private String handlerfunction;
     private String schedule;
     private long status;

    public MdlEventsHandlers() {
    }

	
    public MdlEventsHandlers(String eventname, String handlermodule, String handlerfile, long status) {
        this.eventname = eventname;
        this.handlermodule = handlermodule;
        this.handlerfile = handlerfile;
        this.status = status;
    }
    public MdlEventsHandlers(String eventname, String handlermodule, String handlerfile, String handlerfunction, String schedule, long status) {
       this.eventname = eventname;
       this.handlermodule = handlermodule;
       this.handlerfile = handlerfile;
       this.handlerfunction = handlerfunction;
       this.schedule = schedule;
       this.status = status;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getEventname() {
        return this.eventname;
    }
    
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }
    public String getHandlermodule() {
        return this.handlermodule;
    }
    
    public void setHandlermodule(String handlermodule) {
        this.handlermodule = handlermodule;
    }
    public String getHandlerfile() {
        return this.handlerfile;
    }
    
    public void setHandlerfile(String handlerfile) {
        this.handlerfile = handlerfile;
    }
    public String getHandlerfunction() {
        return this.handlerfunction;
    }
    
    public void setHandlerfunction(String handlerfunction) {
        this.handlerfunction = handlerfunction;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public long getStatus() {
        return this.status;
    }
    
    public void setStatus(long status) {
        this.status = status;
    }




}


