package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEventsQueueHandlers generated by hbm2java
 */
public class MdlEventsQueueHandlers  implements java.io.Serializable {


     private Long id;
     private long queuedeventid;
     private long handlerid;
     private Long status;
     private String errormessage;
     private long timemodified;

    public MdlEventsQueueHandlers() {
    }

	
    public MdlEventsQueueHandlers(long queuedeventid, long handlerid, long timemodified) {
        this.queuedeventid = queuedeventid;
        this.handlerid = handlerid;
        this.timemodified = timemodified;
    }
    public MdlEventsQueueHandlers(long queuedeventid, long handlerid, Long status, String errormessage, long timemodified) {
       this.queuedeventid = queuedeventid;
       this.handlerid = handlerid;
       this.status = status;
       this.errormessage = errormessage;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQueuedeventid() {
        return this.queuedeventid;
    }
    
    public void setQueuedeventid(long queuedeventid) {
        this.queuedeventid = queuedeventid;
    }
    public long getHandlerid() {
        return this.handlerid;
    }
    
    public void setHandlerid(long handlerid) {
        this.handlerid = handlerid;
    }
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    public String getErrormessage() {
        return this.errormessage;
    }
    
    public void setErrormessage(String errormessage) {
        this.errormessage = errormessage;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


