package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEnrolAuthorize generated by hbm2java
 */
public class MdlEnrolAuthorize  implements java.io.Serializable {


     private Long id;
     private String paymentmethod;
     private short refundinfo;
     private String ccname;
     private long courseid;
     private long userid;
     private long transid;
     private long status;
     private long timecreated;
     private long settletime;
     private String amount;
     private String currency;

    public MdlEnrolAuthorize() {
    }

    public MdlEnrolAuthorize(String paymentmethod, short refundinfo, String ccname, long courseid, long userid, long transid, long status, long timecreated, long settletime, String amount, String currency) {
       this.paymentmethod = paymentmethod;
       this.refundinfo = refundinfo;
       this.ccname = ccname;
       this.courseid = courseid;
       this.userid = userid;
       this.transid = transid;
       this.status = status;
       this.timecreated = timecreated;
       this.settletime = settletime;
       this.amount = amount;
       this.currency = currency;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPaymentmethod() {
        return this.paymentmethod;
    }
    
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod;
    }
    public short getRefundinfo() {
        return this.refundinfo;
    }
    
    public void setRefundinfo(short refundinfo) {
        this.refundinfo = refundinfo;
    }
    public String getCcname() {
        return this.ccname;
    }
    
    public void setCcname(String ccname) {
        this.ccname = ccname;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getTransid() {
        return this.transid;
    }
    
    public void setTransid(long transid) {
        this.transid = transid;
    }
    public long getStatus() {
        return this.status;
    }
    
    public void setStatus(long status) {
        this.status = status;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getSettletime() {
        return this.settletime;
    }
    
    public void setSettletime(long settletime) {
        this.settletime = settletime;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


