package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEventsQueue generated by hbm2java
 */
public class MdlEventsQueue  implements java.io.Serializable {


     private Long id;
     private String eventdata;
     private String stackdump;
     private Long userid;
     private long timecreated;

    public MdlEventsQueue() {
    }

	
    public MdlEventsQueue(String eventdata, long timecreated) {
        this.eventdata = eventdata;
        this.timecreated = timecreated;
    }
    public MdlEventsQueue(String eventdata, String stackdump, Long userid, long timecreated) {
       this.eventdata = eventdata;
       this.stackdump = stackdump;
       this.userid = userid;
       this.timecreated = timecreated;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getEventdata() {
        return this.eventdata;
    }
    
    public void setEventdata(String eventdata) {
        this.eventdata = eventdata;
    }
    public String getStackdump() {
        return this.stackdump;
    }
    
    public void setStackdump(String stackdump) {
        this.stackdump = stackdump;
    }
    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }




}


