package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEnrolPaypal generated by hbm2java
 */
public class MdlEnrolPaypal  implements java.io.Serializable {


     private Long id;
     private String business;
     private String receiverEmail;
     private String receiverId;
     private String itemName;
     private long courseid;
     private long userid;
     private String memo;
     private String tax;
     private String optionName1;
     private String optionSelection1X;
     private String optionName2;
     private String optionSelection2X;
     private String paymentStatus;
     private String pendingReason;
     private String reasonCode;
     private String txnId;
     private String parentTxnId;
     private String paymentType;
     private long timeupdated;

    public MdlEnrolPaypal() {
    }

    public MdlEnrolPaypal(String business, String receiverEmail, String receiverId, String itemName, long courseid, long userid, String memo, String tax, String optionName1, String optionSelection1X, String optionName2, String optionSelection2X, String paymentStatus, String pendingReason, String reasonCode, String txnId, String parentTxnId, String paymentType, long timeupdated) {
       this.business = business;
       this.receiverEmail = receiverEmail;
       this.receiverId = receiverId;
       this.itemName = itemName;
       this.courseid = courseid;
       this.userid = userid;
       this.memo = memo;
       this.tax = tax;
       this.optionName1 = optionName1;
       this.optionSelection1X = optionSelection1X;
       this.optionName2 = optionName2;
       this.optionSelection2X = optionSelection2X;
       this.paymentStatus = paymentStatus;
       this.pendingReason = pendingReason;
       this.reasonCode = reasonCode;
       this.txnId = txnId;
       this.parentTxnId = parentTxnId;
       this.paymentType = paymentType;
       this.timeupdated = timeupdated;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getBusiness() {
        return this.business;
    }
    
    public void setBusiness(String business) {
        this.business = business;
    }
    public String getReceiverEmail() {
        return this.receiverEmail;
    }
    
    public void setReceiverEmail(String receiverEmail) {
        this.receiverEmail = receiverEmail;
    }
    public String getReceiverId() {
        return this.receiverId;
    }
    
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    public String getTax() {
        return this.tax;
    }
    
    public void setTax(String tax) {
        this.tax = tax;
    }
    public String getOptionName1() {
        return this.optionName1;
    }
    
    public void setOptionName1(String optionName1) {
        this.optionName1 = optionName1;
    }
    public String getOptionSelection1X() {
        return this.optionSelection1X;
    }
    
    public void setOptionSelection1X(String optionSelection1X) {
        this.optionSelection1X = optionSelection1X;
    }
    public String getOptionName2() {
        return this.optionName2;
    }
    
    public void setOptionName2(String optionName2) {
        this.optionName2 = optionName2;
    }
    public String getOptionSelection2X() {
        return this.optionSelection2X;
    }
    
    public void setOptionSelection2X(String optionSelection2X) {
        this.optionSelection2X = optionSelection2X;
    }
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public String getPendingReason() {
        return this.pendingReason;
    }
    
    public void setPendingReason(String pendingReason) {
        this.pendingReason = pendingReason;
    }
    public String getReasonCode() {
        return this.reasonCode;
    }
    
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }
    public String getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }
    public String getParentTxnId() {
        return this.parentTxnId;
    }
    
    public void setParentTxnId(String parentTxnId) {
        this.parentTxnId = parentTxnId;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public long getTimeupdated() {
        return this.timeupdated;
    }
    
    public void setTimeupdated(long timeupdated) {
        this.timeupdated = timeupdated;
    }




}


