package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlEvent generated by hbm2java
 */
public class MdlEvent  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private short format;
     private long courseid;
     private long groupid;
     private long userid;
     private long repeatid;
     private String modulename;
     private long instance;
     private String eventtype;
     private long timestart;
     private long timeduration;
     private short visible;
     private String uuid;
     private long sequence;
     private long timemodified;

    public MdlEvent() {
    }

    public MdlEvent(String name, String description, short format, long courseid, long groupid, long userid, long repeatid, String modulename, long instance, String eventtype, long timestart, long timeduration, short visible, String uuid, long sequence, long timemodified) {
       this.name = name;
       this.description = description;
       this.format = format;
       this.courseid = courseid;
       this.groupid = groupid;
       this.userid = userid;
       this.repeatid = repeatid;
       this.modulename = modulename;
       this.instance = instance;
       this.eventtype = eventtype;
       this.timestart = timestart;
       this.timeduration = timeduration;
       this.visible = visible;
       this.uuid = uuid;
       this.sequence = sequence;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public short getFormat() {
        return this.format;
    }
    
    public void setFormat(short format) {
        this.format = format;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getRepeatid() {
        return this.repeatid;
    }
    
    public void setRepeatid(long repeatid) {
        this.repeatid = repeatid;
    }
    public String getModulename() {
        return this.modulename;
    }
    
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }
    public long getInstance() {
        return this.instance;
    }
    
    public void setInstance(long instance) {
        this.instance = instance;
    }
    public String getEventtype() {
        return this.eventtype;
    }
    
    public void setEventtype(String eventtype) {
        this.eventtype = eventtype;
    }
    public long getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }
    public long getTimeduration() {
        return this.timeduration;
    }
    
    public void setTimeduration(long timeduration) {
        this.timeduration = timeduration;
    }
    public short getVisible() {
        return this.visible;
    }
    
    public void setVisible(short visible) {
        this.visible = visible;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public long getSequence() {
        return this.sequence;
    }
    
    public void setSequence(long sequence) {
        this.sequence = sequence;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


