package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlForumTrackPrefs generated by hbm2java
 */
public class MdlForumTrackPrefs  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long forumid;

    public MdlForumTrackPrefs() {
    }

    public MdlForumTrackPrefs(long userid, long forumid) {
       this.userid = userid;
       this.forumid = forumid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getForumid() {
        return this.forumid;
    }
    
    public void setForumid(long forumid) {
        this.forumid = forumid;
    }




}


