package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlForumQueue generated by hbm2java
 */
public class MdlForumQueue  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long discussionid;
     private long postid;
     private long timemodified;

    public MdlForumQueue() {
    }

    public MdlForumQueue(long userid, long discussionid, long postid, long timemodified) {
       this.userid = userid;
       this.discussionid = discussionid;
       this.postid = postid;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getDiscussionid() {
        return this.discussionid;
    }
    
    public void setDiscussionid(long discussionid) {
        this.discussionid = discussionid;
    }
    public long getPostid() {
        return this.postid;
    }
    
    public void setPostid(long postid) {
        this.postid = postid;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


