package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlForumDiscussions generated by hbm2java
 */
public class MdlForumDiscussions  implements java.io.Serializable {


     private Long id;
     private long course;
     private long forum;
     private String name;
     private long firstpost;
     private long userid;
     private long groupid;
     private boolean assessed;
     private long timemodified;
     private long usermodified;
     private long timestart;
     private long timeend;

    public MdlForumDiscussions() {
    }

    public MdlForumDiscussions(long course, long forum, String name, long firstpost, long userid, long groupid, boolean assessed, long timemodified, long usermodified, long timestart, long timeend) {
       this.course = course;
       this.forum = forum;
       this.name = name;
       this.firstpost = firstpost;
       this.userid = userid;
       this.groupid = groupid;
       this.assessed = assessed;
       this.timemodified = timemodified;
       this.usermodified = usermodified;
       this.timestart = timestart;
       this.timeend = timeend;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getForum() {
        return this.forum;
    }
    
    public void setForum(long forum) {
        this.forum = forum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getFirstpost() {
        return this.firstpost;
    }
    
    public void setFirstpost(long firstpost) {
        this.firstpost = firstpost;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public boolean isAssessed() {
        return this.assessed;
    }
    
    public void setAssessed(boolean assessed) {
        this.assessed = assessed;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public long getUsermodified() {
        return this.usermodified;
    }
    
    public void setUsermodified(long usermodified) {
        this.usermodified = usermodified;
    }
    public long getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }
    public long getTimeend() {
        return this.timeend;
    }
    
    public void setTimeend(long timeend) {
        this.timeend = timeend;
    }




}


