package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlForumRatings generated by hbm2java
 */
public class MdlForumRatings  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long post;
     private long time;
     private short rating;

    public MdlForumRatings() {
    }

    public MdlForumRatings(long userid, long post, long time, short rating) {
       this.userid = userid;
       this.post = post;
       this.time = time;
       this.rating = rating;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getPost() {
        return this.post;
    }
    
    public void setPost(long post) {
        this.post = post;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public short getRating() {
        return this.rating;
    }
    
    public void setRating(short rating) {
        this.rating = rating;
    }




}


