package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGlossaryCategories generated by hbm2java
 */
public class MdlGlossaryCategories  implements java.io.Serializable {


     private Long id;
     private long glossaryid;
     private String name;
     private byte usedynalink;

    public MdlGlossaryCategories() {
    }

    public MdlGlossaryCategories(long glossaryid, String name, byte usedynalink) {
       this.glossaryid = glossaryid;
       this.name = name;
       this.usedynalink = usedynalink;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getGlossaryid() {
        return this.glossaryid;
    }
    
    public void setGlossaryid(long glossaryid) {
        this.glossaryid = glossaryid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getUsedynalink() {
        return this.usedynalink;
    }
    
    public void setUsedynalink(byte usedynalink) {
        this.usedynalink = usedynalink;
    }




}


