package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGroupings generated by hbm2java
 */
public class MdlGroupings  implements java.io.Serializable {


     private Long id;
     private long courseid;
     private String name;
     private String description;
     private String configdata;
     private long timecreated;
     private long timemodified;

    public MdlGroupings() {
    }

	
    public MdlGroupings(long courseid, String name, long timecreated, long timemodified) {
        this.courseid = courseid;
        this.name = name;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
    }
    public MdlGroupings(long courseid, String name, String description, String configdata, long timecreated, long timemodified) {
       this.courseid = courseid;
       this.name = name;
       this.description = description;
       this.configdata = configdata;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getConfigdata() {
        return this.configdata;
    }
    
    public void setConfigdata(String configdata) {
        this.configdata = configdata;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


