package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGradeCategories generated by hbm2java
 */
public class MdlGradeCategories  implements java.io.Serializable {


     private Long id;
     private long courseid;
     private Long parent;
     private long depth;
     private String path;
     private String fullname;
     private long aggregation;
     private long keephigh;
     private long droplow;
     private boolean aggregateonlygraded;
     private boolean aggregateoutcomes;
     private boolean aggregatesubcats;
     private long timecreated;
     private long timemodified;

    public MdlGradeCategories() {
    }

	
    public MdlGradeCategories(long courseid, long depth, String fullname, long aggregation, long keephigh, long droplow, boolean aggregateonlygraded, boolean aggregateoutcomes, boolean aggregatesubcats, long timecreated, long timemodified) {
        this.courseid = courseid;
        this.depth = depth;
        this.fullname = fullname;
        this.aggregation = aggregation;
        this.keephigh = keephigh;
        this.droplow = droplow;
        this.aggregateonlygraded = aggregateonlygraded;
        this.aggregateoutcomes = aggregateoutcomes;
        this.aggregatesubcats = aggregatesubcats;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
    }
    public MdlGradeCategories(long courseid, Long parent, long depth, String path, String fullname, long aggregation, long keephigh, long droplow, boolean aggregateonlygraded, boolean aggregateoutcomes, boolean aggregatesubcats, long timecreated, long timemodified) {
       this.courseid = courseid;
       this.parent = parent;
       this.depth = depth;
       this.path = path;
       this.fullname = fullname;
       this.aggregation = aggregation;
       this.keephigh = keephigh;
       this.droplow = droplow;
       this.aggregateonlygraded = aggregateonlygraded;
       this.aggregateoutcomes = aggregateoutcomes;
       this.aggregatesubcats = aggregatesubcats;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public Long getParent() {
        return this.parent;
    }
    
    public void setParent(Long parent) {
        this.parent = parent;
    }
    public long getDepth() {
        return this.depth;
    }
    
    public void setDepth(long depth) {
        this.depth = depth;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public long getAggregation() {
        return this.aggregation;
    }
    
    public void setAggregation(long aggregation) {
        this.aggregation = aggregation;
    }
    public long getKeephigh() {
        return this.keephigh;
    }
    
    public void setKeephigh(long keephigh) {
        this.keephigh = keephigh;
    }
    public long getDroplow() {
        return this.droplow;
    }
    
    public void setDroplow(long droplow) {
        this.droplow = droplow;
    }
    public boolean isAggregateonlygraded() {
        return this.aggregateonlygraded;
    }
    
    public void setAggregateonlygraded(boolean aggregateonlygraded) {
        this.aggregateonlygraded = aggregateonlygraded;
    }
    public boolean isAggregateoutcomes() {
        return this.aggregateoutcomes;
    }
    
    public void setAggregateoutcomes(boolean aggregateoutcomes) {
        this.aggregateoutcomes = aggregateoutcomes;
    }
    public boolean isAggregatesubcats() {
        return this.aggregatesubcats;
    }
    
    public void setAggregatesubcats(boolean aggregatesubcats) {
        this.aggregatesubcats = aggregatesubcats;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


