package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGradeOutcomes generated by hbm2java
 */
public class MdlGradeOutcomes  implements java.io.Serializable {


     private Long id;
     private Long courseid;
     private String shortname;
     private String fullname;
     private Long scaleid;
     private String description;
     private Long timecreated;
     private Long timemodified;
     private Long usermodified;

    public MdlGradeOutcomes() {
    }

	
    public MdlGradeOutcomes(String shortname, String fullname) {
        this.shortname = shortname;
        this.fullname = fullname;
    }
    public MdlGradeOutcomes(Long courseid, String shortname, String fullname, Long scaleid, String description, Long timecreated, Long timemodified, Long usermodified) {
       this.courseid = courseid;
       this.shortname = shortname;
       this.fullname = fullname;
       this.scaleid = scaleid;
       this.description = description;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.usermodified = usermodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(Long courseid) {
        this.courseid = courseid;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Long getScaleid() {
        return this.scaleid;
    }
    
    public void setScaleid(Long scaleid) {
        this.scaleid = scaleid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(Long timecreated) {
        this.timecreated = timecreated;
    }
    public Long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(Long timemodified) {
        this.timemodified = timemodified;
    }
    public Long getUsermodified() {
        return this.usermodified;
    }
    
    public void setUsermodified(Long usermodified) {
        this.usermodified = usermodified;
    }




}


