package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGroupsMembers generated by hbm2java
 */
public class MdlGroupsMembers  implements java.io.Serializable {


     private Long id;
     private long groupid;
     private long userid;
     private long timeadded;

    public MdlGroupsMembers() {
    }

    public MdlGroupsMembers(long groupid, long userid, long timeadded) {
       this.groupid = groupid;
       this.userid = userid;
       this.timeadded = timeadded;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getTimeadded() {
        return this.timeadded;
    }
    
    public void setTimeadded(long timeadded) {
        this.timeadded = timeadded;
    }




}


