package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGlossaryAlias generated by hbm2java
 */
public class MdlGlossaryAlias  implements java.io.Serializable {


     private Long id;
     private long entryid;
     private String alias;

    public MdlGlossaryAlias() {
    }

    public MdlGlossaryAlias(long entryid, String alias) {
       this.entryid = entryid;
       this.alias = alias;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getEntryid() {
        return this.entryid;
    }
    
    public void setEntryid(long entryid) {
        this.entryid = entryid;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }




}


