package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGlossaryComments generated by hbm2java
 */
public class MdlGlossaryComments  implements java.io.Serializable {


     private Long id;
     private long entryid;
     private long userid;
     private String entrycomment;
     private byte format;
     private long timemodified;

    public MdlGlossaryComments() {
    }

    public MdlGlossaryComments(long entryid, long userid, String entrycomment, byte format, long timemodified) {
       this.entryid = entryid;
       this.userid = userid;
       this.entrycomment = entrycomment;
       this.format = format;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getEntryid() {
        return this.entryid;
    }
    
    public void setEntryid(long entryid) {
        this.entryid = entryid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getEntrycomment() {
        return this.entrycomment;
    }
    
    public void setEntrycomment(String entrycomment) {
        this.entrycomment = entrycomment;
    }
    public byte getFormat() {
        return this.format;
    }
    
    public void setFormat(byte format) {
        this.format = format;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


