package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MdlGradeGradesHistory generated by hbm2java
 */
public class MdlGradeGradesHistory  implements java.io.Serializable {


     private Long id;
     private long action;
     private long oldid;
     private String source;
     private Long timemodified;
     private Long loggeduser;
     private long itemid;
     private long userid;
     private BigDecimal rawgrade;
     private BigDecimal rawgrademax;
     private BigDecimal rawgrademin;
     private Long rawscaleid;
     private Long usermodified;
     private BigDecimal finalgrade;
     private long hidden;
     private long locked;
     private long locktime;
     private long exported;
     private long overridden;
     private long excluded;
     private String feedback;
     private long feedbackformat;
     private String information;
     private long informationformat;

    public MdlGradeGradesHistory() {
    }

	
    public MdlGradeGradesHistory(long action, long oldid, long itemid, long userid, BigDecimal rawgrademax, BigDecimal rawgrademin, long hidden, long locked, long locktime, long exported, long overridden, long excluded, long feedbackformat, long informationformat) {
        this.action = action;
        this.oldid = oldid;
        this.itemid = itemid;
        this.userid = userid;
        this.rawgrademax = rawgrademax;
        this.rawgrademin = rawgrademin;
        this.hidden = hidden;
        this.locked = locked;
        this.locktime = locktime;
        this.exported = exported;
        this.overridden = overridden;
        this.excluded = excluded;
        this.feedbackformat = feedbackformat;
        this.informationformat = informationformat;
    }
    public MdlGradeGradesHistory(long action, long oldid, String source, Long timemodified, Long loggeduser, long itemid, long userid, BigDecimal rawgrade, BigDecimal rawgrademax, BigDecimal rawgrademin, Long rawscaleid, Long usermodified, BigDecimal finalgrade, long hidden, long locked, long locktime, long exported, long overridden, long excluded, String feedback, long feedbackformat, String information, long informationformat) {
       this.action = action;
       this.oldid = oldid;
       this.source = source;
       this.timemodified = timemodified;
       this.loggeduser = loggeduser;
       this.itemid = itemid;
       this.userid = userid;
       this.rawgrade = rawgrade;
       this.rawgrademax = rawgrademax;
       this.rawgrademin = rawgrademin;
       this.rawscaleid = rawscaleid;
       this.usermodified = usermodified;
       this.finalgrade = finalgrade;
       this.hidden = hidden;
       this.locked = locked;
       this.locktime = locktime;
       this.exported = exported;
       this.overridden = overridden;
       this.excluded = excluded;
       this.feedback = feedback;
       this.feedbackformat = feedbackformat;
       this.information = information;
       this.informationformat = informationformat;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAction() {
        return this.action;
    }
    
    public void setAction(long action) {
        this.action = action;
    }
    public long getOldid() {
        return this.oldid;
    }
    
    public void setOldid(long oldid) {
        this.oldid = oldid;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(Long timemodified) {
        this.timemodified = timemodified;
    }
    public Long getLoggeduser() {
        return this.loggeduser;
    }
    
    public void setLoggeduser(Long loggeduser) {
        this.loggeduser = loggeduser;
    }
    public long getItemid() {
        return this.itemid;
    }
    
    public void setItemid(long itemid) {
        this.itemid = itemid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public BigDecimal getRawgrade() {
        return this.rawgrade;
    }
    
    public void setRawgrade(BigDecimal rawgrade) {
        this.rawgrade = rawgrade;
    }
    public BigDecimal getRawgrademax() {
        return this.rawgrademax;
    }
    
    public void setRawgrademax(BigDecimal rawgrademax) {
        this.rawgrademax = rawgrademax;
    }
    public BigDecimal getRawgrademin() {
        return this.rawgrademin;
    }
    
    public void setRawgrademin(BigDecimal rawgrademin) {
        this.rawgrademin = rawgrademin;
    }
    public Long getRawscaleid() {
        return this.rawscaleid;
    }
    
    public void setRawscaleid(Long rawscaleid) {
        this.rawscaleid = rawscaleid;
    }
    public Long getUsermodified() {
        return this.usermodified;
    }
    
    public void setUsermodified(Long usermodified) {
        this.usermodified = usermodified;
    }
    public BigDecimal getFinalgrade() {
        return this.finalgrade;
    }
    
    public void setFinalgrade(BigDecimal finalgrade) {
        this.finalgrade = finalgrade;
    }
    public long getHidden() {
        return this.hidden;
    }
    
    public void setHidden(long hidden) {
        this.hidden = hidden;
    }
    public long getLocked() {
        return this.locked;
    }
    
    public void setLocked(long locked) {
        this.locked = locked;
    }
    public long getLocktime() {
        return this.locktime;
    }
    
    public void setLocktime(long locktime) {
        this.locktime = locktime;
    }
    public long getExported() {
        return this.exported;
    }
    
    public void setExported(long exported) {
        this.exported = exported;
    }
    public long getOverridden() {
        return this.overridden;
    }
    
    public void setOverridden(long overridden) {
        this.overridden = overridden;
    }
    public long getExcluded() {
        return this.excluded;
    }
    
    public void setExcluded(long excluded) {
        this.excluded = excluded;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public long getFeedbackformat() {
        return this.feedbackformat;
    }
    
    public void setFeedbackformat(long feedbackformat) {
        this.feedbackformat = feedbackformat;
    }
    public String getInformation() {
        return this.information;
    }
    
    public void setInformation(String information) {
        this.information = information;
    }
    public long getInformationformat() {
        return this.informationformat;
    }
    
    public void setInformationformat(long informationformat) {
        this.informationformat = informationformat;
    }




}


