package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGlossaryEntries generated by hbm2java
 */
public class MdlGlossaryEntries  implements java.io.Serializable {


     private Long id;
     private long glossaryid;
     private long userid;
     private String concept;
     private String definition;
     private byte format;
     private String attachment;
     private long timecreated;
     private long timemodified;
     private byte teacherentry;
     private long sourceglossaryid;
     private byte usedynalink;
     private byte casesensitive;
     private byte fullmatch;
     private byte approved;

    public MdlGlossaryEntries() {
    }

    public MdlGlossaryEntries(long glossaryid, long userid, String concept, String definition, byte format, String attachment, long timecreated, long timemodified, byte teacherentry, long sourceglossaryid, byte usedynalink, byte casesensitive, byte fullmatch, byte approved) {
       this.glossaryid = glossaryid;
       this.userid = userid;
       this.concept = concept;
       this.definition = definition;
       this.format = format;
       this.attachment = attachment;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.teacherentry = teacherentry;
       this.sourceglossaryid = sourceglossaryid;
       this.usedynalink = usedynalink;
       this.casesensitive = casesensitive;
       this.fullmatch = fullmatch;
       this.approved = approved;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getGlossaryid() {
        return this.glossaryid;
    }
    
    public void setGlossaryid(long glossaryid) {
        this.glossaryid = glossaryid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getConcept() {
        return this.concept;
    }
    
    public void setConcept(String concept) {
        this.concept = concept;
    }
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }
    public byte getFormat() {
        return this.format;
    }
    
    public void setFormat(byte format) {
        this.format = format;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public byte getTeacherentry() {
        return this.teacherentry;
    }
    
    public void setTeacherentry(byte teacherentry) {
        this.teacherentry = teacherentry;
    }
    public long getSourceglossaryid() {
        return this.sourceglossaryid;
    }
    
    public void setSourceglossaryid(long sourceglossaryid) {
        this.sourceglossaryid = sourceglossaryid;
    }
    public byte getUsedynalink() {
        return this.usedynalink;
    }
    
    public void setUsedynalink(byte usedynalink) {
        this.usedynalink = usedynalink;
    }
    public byte getCasesensitive() {
        return this.casesensitive;
    }
    
    public void setCasesensitive(byte casesensitive) {
        this.casesensitive = casesensitive;
    }
    public byte getFullmatch() {
        return this.fullmatch;
    }
    
    public void setFullmatch(byte fullmatch) {
        this.fullmatch = fullmatch;
    }
    public byte getApproved() {
        return this.approved;
    }
    
    public void setApproved(byte approved) {
        this.approved = approved;
    }




}


