package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGradeImportNewitem generated by hbm2java
 */
public class MdlGradeImportNewitem  implements java.io.Serializable {


     private Long id;
     private String itemname;
     private long importcode;
     private long importer;

    public MdlGradeImportNewitem() {
    }

    public MdlGradeImportNewitem(String itemname, long importcode, long importer) {
       this.itemname = itemname;
       this.importcode = importcode;
       this.importer = importer;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }
    public long getImportcode() {
        return this.importcode;
    }
    
    public void setImportcode(long importcode) {
        this.importcode = importcode;
    }
    public long getImporter() {
        return this.importer;
    }
    
    public void setImporter(long importer) {
        this.importer = importer;
    }




}


