package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MdlGradeItems generated by hbm2java
 */
public class MdlGradeItems  implements java.io.Serializable {


     private Long id;
     private Long courseid;
     private Long categoryid;
     private String itemname;
     private String itemtype;
     private String itemmodule;
     private Long iteminstance;
     private Long itemnumber;
     private String iteminfo;
     private String idnumber;
     private String calculation;
     private short gradetype;
     private BigDecimal grademax;
     private BigDecimal grademin;
     private Long scaleid;
     private Long outcomeid;
     private BigDecimal gradepass;
     private BigDecimal multfactor;
     private BigDecimal plusfactor;
     private BigDecimal aggregationcoef;
     private long sortorder;
     private long display;
     private Boolean decimals;
     private long hidden;
     private long locked;
     private long locktime;
     private long needsupdate;
     private Long timecreated;
     private Long timemodified;

    public MdlGradeItems() {
    }

	
    public MdlGradeItems(String itemtype, short gradetype, BigDecimal grademax, BigDecimal grademin, BigDecimal gradepass, BigDecimal multfactor, BigDecimal plusfactor, BigDecimal aggregationcoef, long sortorder, long display, long hidden, long locked, long locktime, long needsupdate) {
        this.itemtype = itemtype;
        this.gradetype = gradetype;
        this.grademax = grademax;
        this.grademin = grademin;
        this.gradepass = gradepass;
        this.multfactor = multfactor;
        this.plusfactor = plusfactor;
        this.aggregationcoef = aggregationcoef;
        this.sortorder = sortorder;
        this.display = display;
        this.hidden = hidden;
        this.locked = locked;
        this.locktime = locktime;
        this.needsupdate = needsupdate;
    }
    public MdlGradeItems(Long courseid, Long categoryid, String itemname, String itemtype, String itemmodule, Long iteminstance, Long itemnumber, String iteminfo, String idnumber, String calculation, short gradetype, BigDecimal grademax, BigDecimal grademin, Long scaleid, Long outcomeid, BigDecimal gradepass, BigDecimal multfactor, BigDecimal plusfactor, BigDecimal aggregationcoef, long sortorder, long display, Boolean decimals, long hidden, long locked, long locktime, long needsupdate, Long timecreated, Long timemodified) {
       this.courseid = courseid;
       this.categoryid = categoryid;
       this.itemname = itemname;
       this.itemtype = itemtype;
       this.itemmodule = itemmodule;
       this.iteminstance = iteminstance;
       this.itemnumber = itemnumber;
       this.iteminfo = iteminfo;
       this.idnumber = idnumber;
       this.calculation = calculation;
       this.gradetype = gradetype;
       this.grademax = grademax;
       this.grademin = grademin;
       this.scaleid = scaleid;
       this.outcomeid = outcomeid;
       this.gradepass = gradepass;
       this.multfactor = multfactor;
       this.plusfactor = plusfactor;
       this.aggregationcoef = aggregationcoef;
       this.sortorder = sortorder;
       this.display = display;
       this.decimals = decimals;
       this.hidden = hidden;
       this.locked = locked;
       this.locktime = locktime;
       this.needsupdate = needsupdate;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(Long courseid) {
        this.courseid = courseid;
    }
    public Long getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }
    public String getItemtype() {
        return this.itemtype;
    }
    
    public void setItemtype(String itemtype) {
        this.itemtype = itemtype;
    }
    public String getItemmodule() {
        return this.itemmodule;
    }
    
    public void setItemmodule(String itemmodule) {
        this.itemmodule = itemmodule;
    }
    public Long getIteminstance() {
        return this.iteminstance;
    }
    
    public void setIteminstance(Long iteminstance) {
        this.iteminstance = iteminstance;
    }
    public Long getItemnumber() {
        return this.itemnumber;
    }
    
    public void setItemnumber(Long itemnumber) {
        this.itemnumber = itemnumber;
    }
    public String getIteminfo() {
        return this.iteminfo;
    }
    
    public void setIteminfo(String iteminfo) {
        this.iteminfo = iteminfo;
    }
    public String getIdnumber() {
        return this.idnumber;
    }
    
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }
    public String getCalculation() {
        return this.calculation;
    }
    
    public void setCalculation(String calculation) {
        this.calculation = calculation;
    }
    public short getGradetype() {
        return this.gradetype;
    }
    
    public void setGradetype(short gradetype) {
        this.gradetype = gradetype;
    }
    public BigDecimal getGrademax() {
        return this.grademax;
    }
    
    public void setGrademax(BigDecimal grademax) {
        this.grademax = grademax;
    }
    public BigDecimal getGrademin() {
        return this.grademin;
    }
    
    public void setGrademin(BigDecimal grademin) {
        this.grademin = grademin;
    }
    public Long getScaleid() {
        return this.scaleid;
    }
    
    public void setScaleid(Long scaleid) {
        this.scaleid = scaleid;
    }
    public Long getOutcomeid() {
        return this.outcomeid;
    }
    
    public void setOutcomeid(Long outcomeid) {
        this.outcomeid = outcomeid;
    }
    public BigDecimal getGradepass() {
        return this.gradepass;
    }
    
    public void setGradepass(BigDecimal gradepass) {
        this.gradepass = gradepass;
    }
    public BigDecimal getMultfactor() {
        return this.multfactor;
    }
    
    public void setMultfactor(BigDecimal multfactor) {
        this.multfactor = multfactor;
    }
    public BigDecimal getPlusfactor() {
        return this.plusfactor;
    }
    
    public void setPlusfactor(BigDecimal plusfactor) {
        this.plusfactor = plusfactor;
    }
    public BigDecimal getAggregationcoef() {
        return this.aggregationcoef;
    }
    
    public void setAggregationcoef(BigDecimal aggregationcoef) {
        this.aggregationcoef = aggregationcoef;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }
    public long getDisplay() {
        return this.display;
    }
    
    public void setDisplay(long display) {
        this.display = display;
    }
    public Boolean getDecimals() {
        return this.decimals;
    }
    
    public void setDecimals(Boolean decimals) {
        this.decimals = decimals;
    }
    public long getHidden() {
        return this.hidden;
    }
    
    public void setHidden(long hidden) {
        this.hidden = hidden;
    }
    public long getLocked() {
        return this.locked;
    }
    
    public void setLocked(long locked) {
        this.locked = locked;
    }
    public long getLocktime() {
        return this.locktime;
    }
    
    public void setLocktime(long locktime) {
        this.locktime = locktime;
    }
    public long getNeedsupdate() {
        return this.needsupdate;
    }
    
    public void setNeedsupdate(long needsupdate) {
        this.needsupdate = needsupdate;
    }
    public Long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(Long timecreated) {
        this.timecreated = timecreated;
    }
    public Long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(Long timemodified) {
        this.timemodified = timemodified;
    }




}


