package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGroupingsGroups generated by hbm2java
 */
public class MdlGroupingsGroups  implements java.io.Serializable {


     private Long id;
     private long groupingid;
     private long groupid;
     private long timeadded;

    public MdlGroupingsGroups() {
    }

    public MdlGroupingsGroups(long groupingid, long groupid, long timeadded) {
       this.groupingid = groupingid;
       this.groupid = groupid;
       this.timeadded = timeadded;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getGroupingid() {
        return this.groupingid;
    }
    
    public void setGroupingid(long groupingid) {
        this.groupingid = groupingid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getTimeadded() {
        return this.timeadded;
    }
    
    public void setTimeadded(long timeadded) {
        this.timeadded = timeadded;
    }




}


