package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MdlGradeLetters generated by hbm2java
 */
public class MdlGradeLetters  implements java.io.Serializable {


     private Long id;
     private long contextid;
     private BigDecimal lowerboundary;
     private String letter;

    public MdlGradeLetters() {
    }

    public MdlGradeLetters(long contextid, BigDecimal lowerboundary, String letter) {
       this.contextid = contextid;
       this.lowerboundary = lowerboundary;
       this.letter = letter;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getContextid() {
        return this.contextid;
    }
    
    public void setContextid(long contextid) {
        this.contextid = contextid;
    }
    public BigDecimal getLowerboundary() {
        return this.lowerboundary;
    }
    
    public void setLowerboundary(BigDecimal lowerboundary) {
        this.lowerboundary = lowerboundary;
    }
    public String getLetter() {
        return this.letter;
    }
    
    public void setLetter(String letter) {
        this.letter = letter;
    }




}


