package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlGradeCategoriesHistory generated by hbm2java
 */
public class MdlGradeCategoriesHistory  implements java.io.Serializable {


     private Long id;
     private long action;
     private long oldid;
     private String source;
     private Long timemodified;
     private Long loggeduser;
     private long courseid;
     private Long parent;
     private long depth;
     private String path;
     private String fullname;
     private long aggregation;
     private long keephigh;
     private long droplow;
     private boolean aggregateonlygraded;
     private boolean aggregateoutcomes;
     private boolean aggregatesubcats;

    public MdlGradeCategoriesHistory() {
    }

	
    public MdlGradeCategoriesHistory(long action, long oldid, long courseid, long depth, String fullname, long aggregation, long keephigh, long droplow, boolean aggregateonlygraded, boolean aggregateoutcomes, boolean aggregatesubcats) {
        this.action = action;
        this.oldid = oldid;
        this.courseid = courseid;
        this.depth = depth;
        this.fullname = fullname;
        this.aggregation = aggregation;
        this.keephigh = keephigh;
        this.droplow = droplow;
        this.aggregateonlygraded = aggregateonlygraded;
        this.aggregateoutcomes = aggregateoutcomes;
        this.aggregatesubcats = aggregatesubcats;
    }
    public MdlGradeCategoriesHistory(long action, long oldid, String source, Long timemodified, Long loggeduser, long courseid, Long parent, long depth, String path, String fullname, long aggregation, long keephigh, long droplow, boolean aggregateonlygraded, boolean aggregateoutcomes, boolean aggregatesubcats) {
       this.action = action;
       this.oldid = oldid;
       this.source = source;
       this.timemodified = timemodified;
       this.loggeduser = loggeduser;
       this.courseid = courseid;
       this.parent = parent;
       this.depth = depth;
       this.path = path;
       this.fullname = fullname;
       this.aggregation = aggregation;
       this.keephigh = keephigh;
       this.droplow = droplow;
       this.aggregateonlygraded = aggregateonlygraded;
       this.aggregateoutcomes = aggregateoutcomes;
       this.aggregatesubcats = aggregatesubcats;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAction() {
        return this.action;
    }
    
    public void setAction(long action) {
        this.action = action;
    }
    public long getOldid() {
        return this.oldid;
    }
    
    public void setOldid(long oldid) {
        this.oldid = oldid;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(Long timemodified) {
        this.timemodified = timemodified;
    }
    public Long getLoggeduser() {
        return this.loggeduser;
    }
    
    public void setLoggeduser(Long loggeduser) {
        this.loggeduser = loggeduser;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public Long getParent() {
        return this.parent;
    }
    
    public void setParent(Long parent) {
        this.parent = parent;
    }
    public long getDepth() {
        return this.depth;
    }
    
    public void setDepth(long depth) {
        this.depth = depth;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public long getAggregation() {
        return this.aggregation;
    }
    
    public void setAggregation(long aggregation) {
        this.aggregation = aggregation;
    }
    public long getKeephigh() {
        return this.keephigh;
    }
    
    public void setKeephigh(long keephigh) {
        this.keephigh = keephigh;
    }
    public long getDroplow() {
        return this.droplow;
    }
    
    public void setDroplow(long droplow) {
        this.droplow = droplow;
    }
    public boolean isAggregateonlygraded() {
        return this.aggregateonlygraded;
    }
    
    public void setAggregateonlygraded(boolean aggregateonlygraded) {
        this.aggregateonlygraded = aggregateonlygraded;
    }
    public boolean isAggregateoutcomes() {
        return this.aggregateoutcomes;
    }
    
    public void setAggregateoutcomes(boolean aggregateoutcomes) {
        this.aggregateoutcomes = aggregateoutcomes;
    }
    public boolean isAggregatesubcats() {
        return this.aggregatesubcats;
    }
    
    public void setAggregatesubcats(boolean aggregatesubcats) {
        this.aggregatesubcats = aggregatesubcats;
    }




}


