package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlHotpot generated by hbm2java
 */
public class MdlHotpot  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String summary;
     private long timeopen;
     private long timeclose;
     private short location;
     private String reference;
     private short outputformat;
     private short navigation;
     private short studentfeedback;
     private String studentfeedbackurl;
     private short forceplugins;
     private short shownextquiz;
     private short review;
     private long grade;
     private short grademethod;
     private int attempts;
     private String password;
     private String subnet;
     private short clickreporting;
     private long timecreated;
     private long timemodified;

    public MdlHotpot() {
    }

    public MdlHotpot(long course, String name, String summary, long timeopen, long timeclose, short location, String reference, short outputformat, short navigation, short studentfeedback, String studentfeedbackurl, short forceplugins, short shownextquiz, short review, long grade, short grademethod, int attempts, String password, String subnet, short clickreporting, long timecreated, long timemodified) {
       this.course = course;
       this.name = name;
       this.summary = summary;
       this.timeopen = timeopen;
       this.timeclose = timeclose;
       this.location = location;
       this.reference = reference;
       this.outputformat = outputformat;
       this.navigation = navigation;
       this.studentfeedback = studentfeedback;
       this.studentfeedbackurl = studentfeedbackurl;
       this.forceplugins = forceplugins;
       this.shownextquiz = shownextquiz;
       this.review = review;
       this.grade = grade;
       this.grademethod = grademethod;
       this.attempts = attempts;
       this.password = password;
       this.subnet = subnet;
       this.clickreporting = clickreporting;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public long getTimeopen() {
        return this.timeopen;
    }
    
    public void setTimeopen(long timeopen) {
        this.timeopen = timeopen;
    }
    public long getTimeclose() {
        return this.timeclose;
    }
    
    public void setTimeclose(long timeclose) {
        this.timeclose = timeclose;
    }
    public short getLocation() {
        return this.location;
    }
    
    public void setLocation(short location) {
        this.location = location;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public short getOutputformat() {
        return this.outputformat;
    }
    
    public void setOutputformat(short outputformat) {
        this.outputformat = outputformat;
    }
    public short getNavigation() {
        return this.navigation;
    }
    
    public void setNavigation(short navigation) {
        this.navigation = navigation;
    }
    public short getStudentfeedback() {
        return this.studentfeedback;
    }
    
    public void setStudentfeedback(short studentfeedback) {
        this.studentfeedback = studentfeedback;
    }
    public String getStudentfeedbackurl() {
        return this.studentfeedbackurl;
    }
    
    public void setStudentfeedbackurl(String studentfeedbackurl) {
        this.studentfeedbackurl = studentfeedbackurl;
    }
    public short getForceplugins() {
        return this.forceplugins;
    }
    
    public void setForceplugins(short forceplugins) {
        this.forceplugins = forceplugins;
    }
    public short getShownextquiz() {
        return this.shownextquiz;
    }
    
    public void setShownextquiz(short shownextquiz) {
        this.shownextquiz = shownextquiz;
    }
    public short getReview() {
        return this.review;
    }
    
    public void setReview(short review) {
        this.review = review;
    }
    public long getGrade() {
        return this.grade;
    }
    
    public void setGrade(long grade) {
        this.grade = grade;
    }
    public short getGrademethod() {
        return this.grademethod;
    }
    
    public void setGrademethod(short grademethod) {
        this.grademethod = grademethod;
    }
    public int getAttempts() {
        return this.attempts;
    }
    
    public void setAttempts(int attempts) {
        this.attempts = attempts;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSubnet() {
        return this.subnet;
    }
    
    public void setSubnet(String subnet) {
        this.subnet = subnet;
    }
    public short getClickreporting() {
        return this.clickreporting;
    }
    
    public void setClickreporting(short clickreporting) {
        this.clickreporting = clickreporting;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


