package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlHotpotResponses generated by hbm2java
 */
public class MdlHotpotResponses  implements java.io.Serializable {


     private Long id;
     private long attempt;
     private long question;
     private int score;
     private int weighting;
     private String correct;
     private String wrong;
     private String ignored;
     private int hints;
     private int clues;
     private int checks;

    public MdlHotpotResponses() {
    }

    public MdlHotpotResponses(long attempt, long question, int score, int weighting, String correct, String wrong, String ignored, int hints, int clues, int checks) {
       this.attempt = attempt;
       this.question = question;
       this.score = score;
       this.weighting = weighting;
       this.correct = correct;
       this.wrong = wrong;
       this.ignored = ignored;
       this.hints = hints;
       this.clues = clues;
       this.checks = checks;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(long attempt) {
        this.attempt = attempt;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    public int getWeighting() {
        return this.weighting;
    }
    
    public void setWeighting(int weighting) {
        this.weighting = weighting;
    }
    public String getCorrect() {
        return this.correct;
    }
    
    public void setCorrect(String correct) {
        this.correct = correct;
    }
    public String getWrong() {
        return this.wrong;
    }
    
    public void setWrong(String wrong) {
        this.wrong = wrong;
    }
    public String getIgnored() {
        return this.ignored;
    }
    
    public void setIgnored(String ignored) {
        this.ignored = ignored;
    }
    public int getHints() {
        return this.hints;
    }
    
    public void setHints(int hints) {
        this.hints = hints;
    }
    public int getClues() {
        return this.clues;
    }
    
    public void setClues(int clues) {
        this.clues = clues;
    }
    public int getChecks() {
        return this.checks;
    }
    
    public void setChecks(int checks) {
        this.checks = checks;
    }




}


