package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlHotpotStrings generated by hbm2java
 */
public class MdlHotpotStrings  implements java.io.Serializable {


     private Long id;
     private String string;
     private String md5key;

    public MdlHotpotStrings() {
    }

    public MdlHotpotStrings(String string, String md5key) {
       this.string = string;
       this.md5key = md5key;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getString() {
        return this.string;
    }
    
    public void setString(String string) {
        this.string = string;
    }
    public String getMd5key() {
        return this.md5key;
    }
    
    public void setMd5key(String md5key) {
        this.md5key = md5key;
    }




}


