package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlHotpotDetails generated by hbm2java
 */
public class MdlHotpotDetails  implements java.io.Serializable {


     private Long id;
     private long attempt;
     private String details;

    public MdlHotpotDetails() {
    }

	
    public MdlHotpotDetails(long attempt) {
        this.attempt = attempt;
    }
    public MdlHotpotDetails(long attempt, String details) {
       this.attempt = attempt;
       this.details = details;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(long attempt) {
        this.attempt = attempt;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


