package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlJournal generated by hbm2java
 */
public class MdlJournal  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String intro;
     private byte introformat;
     private int days;
     private long assessed;
     private long timemodified;

    public MdlJournal() {
    }

    public MdlJournal(long course, String name, String intro, byte introformat, int days, long assessed, long timemodified) {
       this.course = course;
       this.name = name;
       this.intro = intro;
       this.introformat = introformat;
       this.days = days;
       this.assessed = assessed;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public byte getIntroformat() {
        return this.introformat;
    }
    
    public void setIntroformat(byte introformat) {
        this.introformat = introformat;
    }
    public int getDays() {
        return this.days;
    }
    
    public void setDays(int days) {
        this.days = days;
    }
    public long getAssessed() {
        return this.assessed;
    }
    
    public void setAssessed(long assessed) {
        this.assessed = assessed;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


