package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonAnswers generated by hbm2java
 */
public class MdlLessonAnswers  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long pageid;
     private long jumpto;
     private short grade;
     private long score;
     private short flags;
     private long timecreated;
     private long timemodified;
     private String answer;
     private String response;

    public MdlLessonAnswers() {
    }

	
    public MdlLessonAnswers(long lessonid, long pageid, long jumpto, short grade, long score, short flags, long timecreated, long timemodified) {
        this.lessonid = lessonid;
        this.pageid = pageid;
        this.jumpto = jumpto;
        this.grade = grade;
        this.score = score;
        this.flags = flags;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
    }
    public MdlLessonAnswers(long lessonid, long pageid, long jumpto, short grade, long score, short flags, long timecreated, long timemodified, String answer, String response) {
       this.lessonid = lessonid;
       this.pageid = pageid;
       this.jumpto = jumpto;
       this.grade = grade;
       this.score = score;
       this.flags = flags;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.answer = answer;
       this.response = response;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getPageid() {
        return this.pageid;
    }
    
    public void setPageid(long pageid) {
        this.pageid = pageid;
    }
    public long getJumpto() {
        return this.jumpto;
    }
    
    public void setJumpto(long jumpto) {
        this.jumpto = jumpto;
    }
    public short getGrade() {
        return this.grade;
    }
    
    public void setGrade(short grade) {
        this.grade = grade;
    }
    public long getScore() {
        return this.score;
    }
    
    public void setScore(long score) {
        this.score = score;
    }
    public short getFlags() {
        return this.flags;
    }
    
    public void setFlags(short flags) {
        this.flags = flags;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }




}


