package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonPages generated by hbm2java
 */
public class MdlLessonPages  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long prevpageid;
     private long nextpageid;
     private short qtype;
     private short qoption;
     private short layout;
     private short display;
     private long timecreated;
     private long timemodified;
     private String title;
     private String contents;

    public MdlLessonPages() {
    }

    public MdlLessonPages(long lessonid, long prevpageid, long nextpageid, short qtype, short qoption, short layout, short display, long timecreated, long timemodified, String title, String contents) {
       this.lessonid = lessonid;
       this.prevpageid = prevpageid;
       this.nextpageid = nextpageid;
       this.qtype = qtype;
       this.qoption = qoption;
       this.layout = layout;
       this.display = display;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.title = title;
       this.contents = contents;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getPrevpageid() {
        return this.prevpageid;
    }
    
    public void setPrevpageid(long prevpageid) {
        this.prevpageid = prevpageid;
    }
    public long getNextpageid() {
        return this.nextpageid;
    }
    
    public void setNextpageid(long nextpageid) {
        this.nextpageid = nextpageid;
    }
    public short getQtype() {
        return this.qtype;
    }
    
    public void setQtype(short qtype) {
        this.qtype = qtype;
    }
    public short getQoption() {
        return this.qoption;
    }
    
    public void setQoption(short qoption) {
        this.qoption = qoption;
    }
    public short getLayout() {
        return this.layout;
    }
    
    public void setLayout(short layout) {
        this.layout = layout;
    }
    public short getDisplay() {
        return this.display;
    }
    
    public void setDisplay(short display) {
        this.display = display;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


