package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonTimer generated by hbm2java
 */
public class MdlLessonTimer  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long userid;
     private long starttime;
     private long lessontime;

    public MdlLessonTimer() {
    }

    public MdlLessonTimer(long lessonid, long userid, long starttime, long lessontime) {
       this.lessonid = lessonid;
       this.userid = userid;
       this.starttime = starttime;
       this.lessontime = lessontime;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(long starttime) {
        this.starttime = starttime;
    }
    public long getLessontime() {
        return this.lessontime;
    }
    
    public void setLessontime(long lessontime) {
        this.lessontime = lessontime;
    }




}


