package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLams generated by hbm2java
 */
public class MdlLams  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String introduction;
     private Long learningSessionId;
     private long timemodified;

    public MdlLams() {
    }

	
    public MdlLams(long course, String name, String introduction, long timemodified) {
        this.course = course;
        this.name = name;
        this.introduction = introduction;
        this.timemodified = timemodified;
    }
    public MdlLams(long course, String name, String introduction, Long learningSessionId, long timemodified) {
       this.course = course;
       this.name = name;
       this.introduction = introduction;
       this.learningSessionId = learningSessionId;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
    public Long getLearningSessionId() {
        return this.learningSessionId;
    }
    
    public void setLearningSessionId(Long learningSessionId) {
        this.learningSessionId = learningSessionId;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


