package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonGrades generated by hbm2java
 */
public class MdlLessonGrades  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long userid;
     private double grade;
     private short late;
     private long completed;

    public MdlLessonGrades() {
    }

    public MdlLessonGrades(long lessonid, long userid, double grade, short late, long completed) {
       this.lessonid = lessonid;
       this.userid = userid;
       this.grade = grade;
       this.late = late;
       this.completed = completed;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public double getGrade() {
        return this.grade;
    }
    
    public void setGrade(double grade) {
        this.grade = grade;
    }
    public short getLate() {
        return this.late;
    }
    
    public void setLate(short late) {
        this.late = late;
    }
    public long getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(long completed) {
        this.completed = completed;
    }




}


