package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonBranch generated by hbm2java
 */
public class MdlLessonBranch  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long userid;
     private long pageid;
     private long retry;
     private short flag;
     private long timeseen;

    public MdlLessonBranch() {
    }

    public MdlLessonBranch(long lessonid, long userid, long pageid, long retry, short flag, long timeseen) {
       this.lessonid = lessonid;
       this.userid = userid;
       this.pageid = pageid;
       this.retry = retry;
       this.flag = flag;
       this.timeseen = timeseen;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getPageid() {
        return this.pageid;
    }
    
    public void setPageid(long pageid) {
        this.pageid = pageid;
    }
    public long getRetry() {
        return this.retry;
    }
    
    public void setRetry(long retry) {
        this.retry = retry;
    }
    public short getFlag() {
        return this.flag;
    }
    
    public void setFlag(short flag) {
        this.flag = flag;
    }
    public long getTimeseen() {
        return this.timeseen;
    }
    
    public void setTimeseen(long timeseen) {
        this.timeseen = timeseen;
    }




}


