package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonAttempts generated by hbm2java
 */
public class MdlLessonAttempts  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long pageid;
     private long userid;
     private long answerid;
     private short retry;
     private long correct;
     private String useranswer;
     private long timeseen;

    public MdlLessonAttempts() {
    }

	
    public MdlLessonAttempts(long lessonid, long pageid, long userid, long answerid, short retry, long correct, long timeseen) {
        this.lessonid = lessonid;
        this.pageid = pageid;
        this.userid = userid;
        this.answerid = answerid;
        this.retry = retry;
        this.correct = correct;
        this.timeseen = timeseen;
    }
    public MdlLessonAttempts(long lessonid, long pageid, long userid, long answerid, short retry, long correct, String useranswer, long timeseen) {
       this.lessonid = lessonid;
       this.pageid = pageid;
       this.userid = userid;
       this.answerid = answerid;
       this.retry = retry;
       this.correct = correct;
       this.useranswer = useranswer;
       this.timeseen = timeseen;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getPageid() {
        return this.pageid;
    }
    
    public void setPageid(long pageid) {
        this.pageid = pageid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getAnswerid() {
        return this.answerid;
    }
    
    public void setAnswerid(long answerid) {
        this.answerid = answerid;
    }
    public short getRetry() {
        return this.retry;
    }
    
    public void setRetry(short retry) {
        this.retry = retry;
    }
    public long getCorrect() {
        return this.correct;
    }
    
    public void setCorrect(long correct) {
        this.correct = correct;
    }
    public String getUseranswer() {
        return this.useranswer;
    }
    
    public void setUseranswer(String useranswer) {
        this.useranswer = useranswer;
    }
    public long getTimeseen() {
        return this.timeseen;
    }
    
    public void setTimeseen(long timeseen) {
        this.timeseen = timeseen;
    }




}


