package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlLessonHighScores generated by hbm2java
 */
public class MdlLessonHighScores  implements java.io.Serializable {


     private Long id;
     private long lessonid;
     private long userid;
     private long gradeid;
     private String nickname;

    public MdlLessonHighScores() {
    }

    public MdlLessonHighScores(long lessonid, long userid, long gradeid, String nickname) {
       this.lessonid = lessonid;
       this.userid = userid;
       this.gradeid = gradeid;
       this.nickname = nickname;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getLessonid() {
        return this.lessonid;
    }
    
    public void setLessonid(long lessonid) {
        this.lessonid = lessonid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getGradeid() {
        return this.gradeid;
    }
    
    public void setGradeid(long gradeid) {
        this.gradeid = gradeid;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }




}


