package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetSsoAccessControl generated by hbm2java
 */
public class MdlMnetSsoAccessControl  implements java.io.Serializable {


     private Long id;
     private String username;
     private long mnetHostId;
     private String accessctrl;

    public MdlMnetSsoAccessControl() {
    }

    public MdlMnetSsoAccessControl(String username, long mnetHostId, String accessctrl) {
       this.username = username;
       this.mnetHostId = mnetHostId;
       this.accessctrl = accessctrl;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public long getMnetHostId() {
        return this.mnetHostId;
    }
    
    public void setMnetHostId(long mnetHostId) {
        this.mnetHostId = mnetHostId;
    }
    public String getAccessctrl() {
        return this.accessctrl;
    }
    
    public void setAccessctrl(String accessctrl) {
        this.accessctrl = accessctrl;
    }




}


