package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMessage generated by hbm2java
 */
public class MdlMessage  implements java.io.Serializable {


     private Long id;
     private long useridfrom;
     private long useridto;
     private String message;
     private short format;
     private long timecreated;
     private String messagetype;

    public MdlMessage() {
    }

    public MdlMessage(long useridfrom, long useridto, String message, short format, long timecreated, String messagetype) {
       this.useridfrom = useridfrom;
       this.useridto = useridto;
       this.message = message;
       this.format = format;
       this.timecreated = timecreated;
       this.messagetype = messagetype;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUseridfrom() {
        return this.useridfrom;
    }
    
    public void setUseridfrom(long useridfrom) {
        this.useridfrom = useridfrom;
    }
    public long getUseridto() {
        return this.useridto;
    }
    
    public void setUseridto(long useridto) {
        this.useridto = useridto;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public short getFormat() {
        return this.format;
    }
    
    public void setFormat(short format) {
        this.format = format;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public String getMessagetype() {
        return this.messagetype;
    }
    
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }




}


