package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetSession generated by hbm2java
 */
public class MdlMnetSession  implements java.io.Serializable {


     private Long id;
     private long userid;
     private String username;
     private String token;
     private long mnethostid;
     private String useragent;
     private long confirmTimeout;
     private String sessionId;
     private long expires;

    public MdlMnetSession() {
    }

    public MdlMnetSession(long userid, String username, String token, long mnethostid, String useragent, long confirmTimeout, String sessionId, long expires) {
       this.userid = userid;
       this.username = username;
       this.token = token;
       this.mnethostid = mnethostid;
       this.useragent = useragent;
       this.confirmTimeout = confirmTimeout;
       this.sessionId = sessionId;
       this.expires = expires;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public long getMnethostid() {
        return this.mnethostid;
    }
    
    public void setMnethostid(long mnethostid) {
        this.mnethostid = mnethostid;
    }
    public String getUseragent() {
        return this.useragent;
    }
    
    public void setUseragent(String useragent) {
        this.useragent = useragent;
    }
    public long getConfirmTimeout() {
        return this.confirmTimeout;
    }
    
    public void setConfirmTimeout(long confirmTimeout) {
        this.confirmTimeout = confirmTimeout;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public long getExpires() {
        return this.expires;
    }
    
    public void setExpires(long expires) {
        this.expires = expires;
    }




}


