package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetLog generated by hbm2java
 */
public class MdlMnetLog  implements java.io.Serializable {


     private Long id;
     private long hostid;
     private long remoteid;
     private long time;
     private long userid;
     private String ip;
     private long course;
     private String coursename;
     private String module;
     private long cmid;
     private String action;
     private String url;
     private String info;

    public MdlMnetLog() {
    }

    public MdlMnetLog(long hostid, long remoteid, long time, long userid, String ip, long course, String coursename, String module, long cmid, String action, String url, String info) {
       this.hostid = hostid;
       this.remoteid = remoteid;
       this.time = time;
       this.userid = userid;
       this.ip = ip;
       this.course = course;
       this.coursename = coursename;
       this.module = module;
       this.cmid = cmid;
       this.action = action;
       this.url = url;
       this.info = info;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getHostid() {
        return this.hostid;
    }
    
    public void setHostid(long hostid) {
        this.hostid = hostid;
    }
    public long getRemoteid() {
        return this.remoteid;
    }
    
    public void setRemoteid(long remoteid) {
        this.remoteid = remoteid;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public long getCmid() {
        return this.cmid;
    }
    
    public void setCmid(long cmid) {
        this.cmid = cmid;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


