package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetEnrolCourse generated by hbm2java
 */
public class MdlMnetEnrolCourse  implements java.io.Serializable {


     private Long id;
     private long hostid;
     private long remoteid;
     private long catId;
     private String catName;
     private String catDescription;
     private long sortorder;
     private String fullname;
     private String shortname;
     private String idnumber;
     private String summary;
     private long startdate;
     private String cost;
     private String currency;
     private short defaultroleid;
     private String defaultrolename;

    public MdlMnetEnrolCourse() {
    }

    public MdlMnetEnrolCourse(long hostid, long remoteid, long catId, String catName, String catDescription, long sortorder, String fullname, String shortname, String idnumber, String summary, long startdate, String cost, String currency, short defaultroleid, String defaultrolename) {
       this.hostid = hostid;
       this.remoteid = remoteid;
       this.catId = catId;
       this.catName = catName;
       this.catDescription = catDescription;
       this.sortorder = sortorder;
       this.fullname = fullname;
       this.shortname = shortname;
       this.idnumber = idnumber;
       this.summary = summary;
       this.startdate = startdate;
       this.cost = cost;
       this.currency = currency;
       this.defaultroleid = defaultroleid;
       this.defaultrolename = defaultrolename;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getHostid() {
        return this.hostid;
    }
    
    public void setHostid(long hostid) {
        this.hostid = hostid;
    }
    public long getRemoteid() {
        return this.remoteid;
    }
    
    public void setRemoteid(long remoteid) {
        this.remoteid = remoteid;
    }
    public long getCatId() {
        return this.catId;
    }
    
    public void setCatId(long catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public String getCatDescription() {
        return this.catDescription;
    }
    
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getIdnumber() {
        return this.idnumber;
    }
    
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public long getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(long startdate) {
        this.startdate = startdate;
    }
    public String getCost() {
        return this.cost;
    }
    
    public void setCost(String cost) {
        this.cost = cost;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public short getDefaultroleid() {
        return this.defaultroleid;
    }
    
    public void setDefaultroleid(short defaultroleid) {
        this.defaultroleid = defaultroleid;
    }
    public String getDefaultrolename() {
        return this.defaultrolename;
    }
    
    public void setDefaultrolename(String defaultrolename) {
        this.defaultrolename = defaultrolename;
    }




}


