package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetApplication generated by hbm2java
 */
public class MdlMnetApplication  implements java.io.Serializable {


     private Long id;
     private String name;
     private String displayName;
     private String xmlrpcServerUrl;
     private String ssoLandUrl;

    public MdlMnetApplication() {
    }

    public MdlMnetApplication(String name, String displayName, String xmlrpcServerUrl, String ssoLandUrl) {
       this.name = name;
       this.displayName = displayName;
       this.xmlrpcServerUrl = xmlrpcServerUrl;
       this.ssoLandUrl = ssoLandUrl;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getXmlrpcServerUrl() {
        return this.xmlrpcServerUrl;
    }
    
    public void setXmlrpcServerUrl(String xmlrpcServerUrl) {
        this.xmlrpcServerUrl = xmlrpcServerUrl;
    }
    public String getSsoLandUrl() {
        return this.ssoLandUrl;
    }
    
    public void setSsoLandUrl(String ssoLandUrl) {
        this.ssoLandUrl = ssoLandUrl;
    }




}


