package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMessageContacts generated by hbm2java
 */
public class MdlMessageContacts  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long contactid;
     private boolean blocked;

    public MdlMessageContacts() {
    }

    public MdlMessageContacts(long userid, long contactid, boolean blocked) {
       this.userid = userid;
       this.contactid = contactid;
       this.blocked = blocked;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getContactid() {
        return this.contactid;
    }
    
    public void setContactid(long contactid) {
        this.contactid = contactid;
    }
    public boolean isBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(boolean blocked) {
        this.blocked = blocked;
    }




}


