package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetService generated by hbm2java
 */
public class MdlMnetService  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private String apiversion;
     private boolean offer;

    public MdlMnetService() {
    }

    public MdlMnetService(String name, String description, String apiversion, boolean offer) {
       this.name = name;
       this.description = description;
       this.apiversion = apiversion;
       this.offer = offer;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getApiversion() {
        return this.apiversion;
    }
    
    public void setApiversion(String apiversion) {
        this.apiversion = apiversion;
    }
    public boolean isOffer() {
        return this.offer;
    }
    
    public void setOffer(boolean offer) {
        this.offer = offer;
    }




}


