package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetService2rpc generated by hbm2java
 */
public class MdlMnetService2rpc  implements java.io.Serializable {


     private Long id;
     private long serviceid;
     private long rpcid;

    public MdlMnetService2rpc() {
    }

    public MdlMnetService2rpc(long serviceid, long rpcid) {
       this.serviceid = serviceid;
       this.rpcid = rpcid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getServiceid() {
        return this.serviceid;
    }
    
    public void setServiceid(long serviceid) {
        this.serviceid = serviceid;
    }
    public long getRpcid() {
        return this.rpcid;
    }
    
    public void setRpcid(long rpcid) {
        this.rpcid = rpcid;
    }




}


