package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlMnetHost generated by hbm2java
 */
public class MdlMnetHost  implements java.io.Serializable {


     private Long id;
     private boolean deleted;
     private String wwwroot;
     private String ipAddress;
     private String name;
     private String publicKey;
     private long publicKeyExpires;
     private byte transport;
     private int portno;
     private long lastConnectTime;
     private long lastLogId;
     private boolean forceTheme;
     private String theme;
     private long applicationid;

    public MdlMnetHost() {
    }

	
    public MdlMnetHost(boolean deleted, String wwwroot, String ipAddress, String name, String publicKey, long publicKeyExpires, byte transport, int portno, long lastConnectTime, long lastLogId, boolean forceTheme, long applicationid) {
        this.deleted = deleted;
        this.wwwroot = wwwroot;
        this.ipAddress = ipAddress;
        this.name = name;
        this.publicKey = publicKey;
        this.publicKeyExpires = publicKeyExpires;
        this.transport = transport;
        this.portno = portno;
        this.lastConnectTime = lastConnectTime;
        this.lastLogId = lastLogId;
        this.forceTheme = forceTheme;
        this.applicationid = applicationid;
    }
    public MdlMnetHost(boolean deleted, String wwwroot, String ipAddress, String name, String publicKey, long publicKeyExpires, byte transport, int portno, long lastConnectTime, long lastLogId, boolean forceTheme, String theme, long applicationid) {
       this.deleted = deleted;
       this.wwwroot = wwwroot;
       this.ipAddress = ipAddress;
       this.name = name;
       this.publicKey = publicKey;
       this.publicKeyExpires = publicKeyExpires;
       this.transport = transport;
       this.portno = portno;
       this.lastConnectTime = lastConnectTime;
       this.lastLogId = lastLogId;
       this.forceTheme = forceTheme;
       this.theme = theme;
       this.applicationid = applicationid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public String getWwwroot() {
        return this.wwwroot;
    }
    
    public void setWwwroot(String wwwroot) {
        this.wwwroot = wwwroot;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPublicKey() {
        return this.publicKey;
    }
    
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }
    public long getPublicKeyExpires() {
        return this.publicKeyExpires;
    }
    
    public void setPublicKeyExpires(long publicKeyExpires) {
        this.publicKeyExpires = publicKeyExpires;
    }
    public byte getTransport() {
        return this.transport;
    }
    
    public void setTransport(byte transport) {
        this.transport = transport;
    }
    public int getPortno() {
        return this.portno;
    }
    
    public void setPortno(int portno) {
        this.portno = portno;
    }
    public long getLastConnectTime() {
        return this.lastConnectTime;
    }
    
    public void setLastConnectTime(long lastConnectTime) {
        this.lastConnectTime = lastConnectTime;
    }
    public long getLastLogId() {
        return this.lastLogId;
    }
    
    public void setLastLogId(long lastLogId) {
        this.lastLogId = lastLogId;
    }
    public boolean isForceTheme() {
        return this.forceTheme;
    }
    
    public void setForceTheme(boolean forceTheme) {
        this.forceTheme = forceTheme;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    public long getApplicationid() {
        return this.applicationid;
    }
    
    public void setApplicationid(long applicationid) {
        this.applicationid = applicationid;
    }




}


