package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlPost generated by hbm2java
 */
public class MdlPost  implements java.io.Serializable {


     private Long id;
     private String module;
     private long userid;
     private long courseid;
     private long groupid;
     private long moduleid;
     private long coursemoduleid;
     private String subject;
     private String summary;
     private String content;
     private String uniquehash;
     private long rating;
     private long format;
     private String attachment;
     private String publishstate;
     private long lastmodified;
     private long created;
     private Long usermodified;

    public MdlPost() {
    }

	
    public MdlPost(String module, long userid, long courseid, long groupid, long moduleid, long coursemoduleid, String subject, String uniquehash, long rating, long format, String publishstate, long lastmodified, long created) {
        this.module = module;
        this.userid = userid;
        this.courseid = courseid;
        this.groupid = groupid;
        this.moduleid = moduleid;
        this.coursemoduleid = coursemoduleid;
        this.subject = subject;
        this.uniquehash = uniquehash;
        this.rating = rating;
        this.format = format;
        this.publishstate = publishstate;
        this.lastmodified = lastmodified;
        this.created = created;
    }
    public MdlPost(String module, long userid, long courseid, long groupid, long moduleid, long coursemoduleid, String subject, String summary, String content, String uniquehash, long rating, long format, String attachment, String publishstate, long lastmodified, long created, Long usermodified) {
       this.module = module;
       this.userid = userid;
       this.courseid = courseid;
       this.groupid = groupid;
       this.moduleid = moduleid;
       this.coursemoduleid = coursemoduleid;
       this.subject = subject;
       this.summary = summary;
       this.content = content;
       this.uniquehash = uniquehash;
       this.rating = rating;
       this.format = format;
       this.attachment = attachment;
       this.publishstate = publishstate;
       this.lastmodified = lastmodified;
       this.created = created;
       this.usermodified = usermodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getModuleid() {
        return this.moduleid;
    }
    
    public void setModuleid(long moduleid) {
        this.moduleid = moduleid;
    }
    public long getCoursemoduleid() {
        return this.coursemoduleid;
    }
    
    public void setCoursemoduleid(long coursemoduleid) {
        this.coursemoduleid = coursemoduleid;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getUniquehash() {
        return this.uniquehash;
    }
    
    public void setUniquehash(String uniquehash) {
        this.uniquehash = uniquehash;
    }
    public long getRating() {
        return this.rating;
    }
    
    public void setRating(long rating) {
        this.rating = rating;
    }
    public long getFormat() {
        return this.format;
    }
    
    public void setFormat(long format) {
        this.format = format;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
    public String getPublishstate() {
        return this.publishstate;
    }
    
    public void setPublishstate(String publishstate) {
        this.publishstate = publishstate;
    }
    public long getLastmodified() {
        return this.lastmodified;
    }
    
    public void setLastmodified(long lastmodified) {
        this.lastmodified = lastmodified;
    }
    public long getCreated() {
        return this.created;
    }
    
    public void setCreated(long created) {
        this.created = created;
    }
    public Long getUsermodified() {
        return this.usermodified;
    }
    
    public void setUsermodified(Long usermodified) {
        this.usermodified = usermodified;
    }




}


