package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuizGrades generated by hbm2java
 */
public class MdlQuizGrades  implements java.io.Serializable {


     private Long id;
     private long quiz;
     private long userid;
     private double grade;
     private long timemodified;

    public MdlQuizGrades() {
    }

    public MdlQuizGrades(long quiz, long userid, double grade, long timemodified) {
       this.quiz = quiz;
       this.userid = userid;
       this.grade = grade;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(long quiz) {
        this.quiz = quiz;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public double getGrade() {
        return this.grade;
    }
    
    public void setGrade(double grade) {
        this.grade = grade;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


