package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionMultichoice generated by hbm2java
 */
public class MdlQuestionMultichoice  implements java.io.Serializable {


     private Long id;
     private long question;
     private short layout;
     private String answers;
     private short single;
     private short shuffleanswers;
     private String correctfeedback;
     private String partiallycorrectfeedback;
     private String incorrectfeedback;
     private String answernumbering;

    public MdlQuestionMultichoice() {
    }

    public MdlQuestionMultichoice(long question, short layout, String answers, short single, short shuffleanswers, String correctfeedback, String partiallycorrectfeedback, String incorrectfeedback, String answernumbering) {
       this.question = question;
       this.layout = layout;
       this.answers = answers;
       this.single = single;
       this.shuffleanswers = shuffleanswers;
       this.correctfeedback = correctfeedback;
       this.partiallycorrectfeedback = partiallycorrectfeedback;
       this.incorrectfeedback = incorrectfeedback;
       this.answernumbering = answernumbering;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public short getLayout() {
        return this.layout;
    }
    
    public void setLayout(short layout) {
        this.layout = layout;
    }
    public String getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(String answers) {
        this.answers = answers;
    }
    public short getSingle() {
        return this.single;
    }
    
    public void setSingle(short single) {
        this.single = single;
    }
    public short getShuffleanswers() {
        return this.shuffleanswers;
    }
    
    public void setShuffleanswers(short shuffleanswers) {
        this.shuffleanswers = shuffleanswers;
    }
    public String getCorrectfeedback() {
        return this.correctfeedback;
    }
    
    public void setCorrectfeedback(String correctfeedback) {
        this.correctfeedback = correctfeedback;
    }
    public String getPartiallycorrectfeedback() {
        return this.partiallycorrectfeedback;
    }
    
    public void setPartiallycorrectfeedback(String partiallycorrectfeedback) {
        this.partiallycorrectfeedback = partiallycorrectfeedback;
    }
    public String getIncorrectfeedback() {
        return this.incorrectfeedback;
    }
    
    public void setIncorrectfeedback(String incorrectfeedback) {
        this.incorrectfeedback = incorrectfeedback;
    }
    public String getAnswernumbering() {
        return this.answernumbering;
    }
    
    public void setAnswernumbering(String answernumbering) {
        this.answernumbering = answernumbering;
    }




}


