package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionShortanswer generated by hbm2java
 */
public class MdlQuestionShortanswer  implements java.io.Serializable {


     private Long id;
     private long question;
     private String answers;
     private byte usecase;

    public MdlQuestionShortanswer() {
    }

    public MdlQuestionShortanswer(long question, String answers, byte usecase) {
       this.question = question;
       this.answers = answers;
       this.usecase = usecase;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public String getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(String answers) {
        this.answers = answers;
    }
    public byte getUsecase() {
        return this.usecase;
    }
    
    public void setUsecase(byte usecase) {
        this.usecase = usecase;
    }




}


