package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuizQuestionVersions generated by hbm2java
 */
public class MdlQuizQuestionVersions  implements java.io.Serializable {


     private Long id;
     private long timestamp;
     private long quiz;
     private long oldquestion;
     private long newquestion;
     private long originalquestion;
     private long userid;

    public MdlQuizQuestionVersions() {
    }

    public MdlQuizQuestionVersions(long quiz, long oldquestion, long newquestion, long originalquestion, long userid) {
       this.quiz = quiz;
       this.oldquestion = oldquestion;
       this.newquestion = newquestion;
       this.originalquestion = originalquestion;
       this.userid = userid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
    public long getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(long quiz) {
        this.quiz = quiz;
    }
    public long getOldquestion() {
        return this.oldquestion;
    }
    
    public void setOldquestion(long oldquestion) {
        this.oldquestion = oldquestion;
    }
    public long getNewquestion() {
        return this.newquestion;
    }
    
    public void setNewquestion(long newquestion) {
        this.newquestion = newquestion;
    }
    public long getOriginalquestion() {
        return this.originalquestion;
    }
    
    public void setOriginalquestion(long originalquestion) {
        this.originalquestion = originalquestion;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }




}


