package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionSessions generated by hbm2java
 */
public class MdlQuestionSessions  implements java.io.Serializable {


     private Long id;
     private long attemptid;
     private long questionid;
     private long newest;
     private long newgraded;
     private double sumpenalty;
     private String manualcomment;

    public MdlQuestionSessions() {
    }

    public MdlQuestionSessions(long attemptid, long questionid, long newest, long newgraded, double sumpenalty, String manualcomment) {
       this.attemptid = attemptid;
       this.questionid = questionid;
       this.newest = newest;
       this.newgraded = newgraded;
       this.sumpenalty = sumpenalty;
       this.manualcomment = manualcomment;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAttemptid() {
        return this.attemptid;
    }
    
    public void setAttemptid(long attemptid) {
        this.attemptid = attemptid;
    }
    public long getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(long questionid) {
        this.questionid = questionid;
    }
    public long getNewest() {
        return this.newest;
    }
    
    public void setNewest(long newest) {
        this.newest = newest;
    }
    public long getNewgraded() {
        return this.newgraded;
    }
    
    public void setNewgraded(long newgraded) {
        this.newgraded = newgraded;
    }
    public double getSumpenalty() {
        return this.sumpenalty;
    }
    
    public void setSumpenalty(double sumpenalty) {
        this.sumpenalty = sumpenalty;
    }
    public String getManualcomment() {
        return this.manualcomment;
    }
    
    public void setManualcomment(String manualcomment) {
        this.manualcomment = manualcomment;
    }




}


