package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MdlQuestionNumericalUnits generated by hbm2java
 */
public class MdlQuestionNumericalUnits  implements java.io.Serializable {


     private Long id;
     private long question;
     private BigDecimal multiplier;
     private String unit;

    public MdlQuestionNumericalUnits() {
    }

    public MdlQuestionNumericalUnits(long question, BigDecimal multiplier, String unit) {
       this.question = question;
       this.multiplier = multiplier;
       this.unit = unit;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public BigDecimal getMultiplier() {
        return this.multiplier;
    }
    
    public void setMultiplier(BigDecimal multiplier) {
        this.multiplier = multiplier;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }




}


