package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionAnswers generated by hbm2java
 */
public class MdlQuestionAnswers  implements java.io.Serializable {


     private Long id;
     private long question;
     private String answer;
     private double fraction;
     private String feedback;

    public MdlQuestionAnswers() {
    }

    public MdlQuestionAnswers(long question, String answer, double fraction, String feedback) {
       this.question = question;
       this.answer = answer;
       this.fraction = fraction;
       this.feedback = feedback;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public double getFraction() {
        return this.fraction;
    }
    
    public void setFraction(double fraction) {
        this.fraction = fraction;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }




}


