package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuizAttempts generated by hbm2java
 */
public class MdlQuizAttempts  implements java.io.Serializable {


     private Long id;
     private long uniqueid;
     private long quiz;
     private long userid;
     private int attempt;
     private double sumgrades;
     private long timestart;
     private long timefinish;
     private long timemodified;
     private String layout;
     private short preview;

    public MdlQuizAttempts() {
    }

    public MdlQuizAttempts(long uniqueid, long quiz, long userid, int attempt, double sumgrades, long timestart, long timefinish, long timemodified, String layout, short preview) {
       this.uniqueid = uniqueid;
       this.quiz = quiz;
       this.userid = userid;
       this.attempt = attempt;
       this.sumgrades = sumgrades;
       this.timestart = timestart;
       this.timefinish = timefinish;
       this.timemodified = timemodified;
       this.layout = layout;
       this.preview = preview;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUniqueid() {
        return this.uniqueid;
    }
    
    public void setUniqueid(long uniqueid) {
        this.uniqueid = uniqueid;
    }
    public long getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(long quiz) {
        this.quiz = quiz;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public int getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(int attempt) {
        this.attempt = attempt;
    }
    public double getSumgrades() {
        return this.sumgrades;
    }
    
    public void setSumgrades(double sumgrades) {
        this.sumgrades = sumgrades;
    }
    public long getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }
    public long getTimefinish() {
        return this.timefinish;
    }
    
    public void setTimefinish(long timefinish) {
        this.timefinish = timefinish;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public String getLayout() {
        return this.layout;
    }
    
    public void setLayout(String layout) {
        this.layout = layout;
    }
    public short getPreview() {
        return this.preview;
    }
    
    public void setPreview(short preview) {
        this.preview = preview;
    }




}


