package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuizFeedback generated by hbm2java
 */
public class MdlQuizFeedback  implements java.io.Serializable {


     private Long id;
     private long quizid;
     private String feedbacktext;
     private double mingrade;
     private double maxgrade;

    public MdlQuizFeedback() {
    }

    public MdlQuizFeedback(long quizid, String feedbacktext, double mingrade, double maxgrade) {
       this.quizid = quizid;
       this.feedbacktext = feedbacktext;
       this.mingrade = mingrade;
       this.maxgrade = maxgrade;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuizid() {
        return this.quizid;
    }
    
    public void setQuizid(long quizid) {
        this.quizid = quizid;
    }
    public String getFeedbacktext() {
        return this.feedbacktext;
    }
    
    public void setFeedbacktext(String feedbacktext) {
        this.feedbacktext = feedbacktext;
    }
    public double getMingrade() {
        return this.mingrade;
    }
    
    public void setMingrade(double mingrade) {
        this.mingrade = mingrade;
    }
    public double getMaxgrade() {
        return this.maxgrade;
    }
    
    public void setMaxgrade(double maxgrade) {
        this.maxgrade = maxgrade;
    }




}


