package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionStates generated by hbm2java
 */
public class MdlQuestionStates  implements java.io.Serializable {


     private Long id;
     private long timestamp;
     private long attempt;
     private long question;
     private long originalquestion;
     private int seqNumber;
     private String answer;
     private short event;
     private double grade;
     private double rawGrade;
     private double penalty;

    public MdlQuestionStates() {
    }

    public MdlQuestionStates(long attempt, long question, long originalquestion, int seqNumber, String answer, short event, double grade, double rawGrade, double penalty) {
       this.attempt = attempt;
       this.question = question;
       this.originalquestion = originalquestion;
       this.seqNumber = seqNumber;
       this.answer = answer;
       this.event = event;
       this.grade = grade;
       this.rawGrade = rawGrade;
       this.penalty = penalty;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
    public long getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(long attempt) {
        this.attempt = attempt;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public long getOriginalquestion() {
        return this.originalquestion;
    }
    
    public void setOriginalquestion(long originalquestion) {
        this.originalquestion = originalquestion;
    }
    public int getSeqNumber() {
        return this.seqNumber;
    }
    
    public void setSeqNumber(int seqNumber) {
        this.seqNumber = seqNumber;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public short getEvent() {
        return this.event;
    }
    
    public void setEvent(short event) {
        this.event = event;
    }
    public double getGrade() {
        return this.grade;
    }
    
    public void setGrade(double grade) {
        this.grade = grade;
    }
    public double getRawGrade() {
        return this.rawGrade;
    }
    
    public void setRawGrade(double rawGrade) {
        this.rawGrade = rawGrade;
    }
    public double getPenalty() {
        return this.penalty;
    }
    
    public void setPenalty(double penalty) {
        this.penalty = penalty;
    }




}


