package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionDatasets generated by hbm2java
 */
public class MdlQuestionDatasets  implements java.io.Serializable {


     private Long id;
     private long question;
     private long datasetdefinition;

    public MdlQuestionDatasets() {
    }

    public MdlQuestionDatasets(long question, long datasetdefinition) {
       this.question = question;
       this.datasetdefinition = datasetdefinition;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public long getDatasetdefinition() {
        return this.datasetdefinition;
    }
    
    public void setDatasetdefinition(long datasetdefinition) {
        this.datasetdefinition = datasetdefinition;
    }




}


