package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionMatch generated by hbm2java
 */
public class MdlQuestionMatch  implements java.io.Serializable {


     private Long id;
     private long question;
     private String subquestions;
     private short shuffleanswers;

    public MdlQuestionMatch() {
    }

    public MdlQuestionMatch(long question, String subquestions, short shuffleanswers) {
       this.question = question;
       this.subquestions = subquestions;
       this.shuffleanswers = shuffleanswers;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public String getSubquestions() {
        return this.subquestions;
    }
    
    public void setSubquestions(String subquestions) {
        this.subquestions = subquestions;
    }
    public short getShuffleanswers() {
        return this.shuffleanswers;
    }
    
    public void setShuffleanswers(short shuffleanswers) {
        this.shuffleanswers = shuffleanswers;
    }




}


