package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionMultianswer generated by hbm2java
 */
public class MdlQuestionMultianswer  implements java.io.Serializable {


     private Long id;
     private long question;
     private String sequence;

    public MdlQuestionMultianswer() {
    }

    public MdlQuestionMultianswer(long question, String sequence) {
       this.question = question;
       this.sequence = sequence;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public String getSequence() {
        return this.sequence;
    }
    
    public void setSequence(String sequence) {
        this.sequence = sequence;
    }




}


