package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionAttempts generated by hbm2java
 */
public class MdlQuestionAttempts  implements java.io.Serializable {


     private Long id;
     private String modulename;

    public MdlQuestionAttempts() {
    }

    public MdlQuestionAttempts(String modulename) {
       this.modulename = modulename;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getModulename() {
        return this.modulename;
    }
    
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }




}


