package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlQuestionCategories generated by hbm2java
 */
public class MdlQuestionCategories  implements java.io.Serializable {


     private Long id;
     private String name;
     private long contextid;
     private String info;
     private String stamp;
     private long parent;
     private long sortorder;

    public MdlQuestionCategories() {
    }

    public MdlQuestionCategories(String name, long contextid, String info, String stamp, long parent, long sortorder) {
       this.name = name;
       this.contextid = contextid;
       this.info = info;
       this.stamp = stamp;
       this.parent = parent;
       this.sortorder = sortorder;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getContextid() {
        return this.contextid;
    }
    
    public void setContextid(long contextid) {
        this.contextid = contextid;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getStamp() {
        return this.stamp;
    }
    
    public void setStamp(String stamp) {
        this.stamp = stamp;
    }
    public long getParent() {
        return this.parent;
    }
    
    public void setParent(long parent) {
        this.parent = parent;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }




}


