package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlRoleCapabilities generated by hbm2java
 */
public class MdlRoleCapabilities  implements java.io.Serializable {


     private Long id;
     private long contextid;
     private long roleid;
     private String capability;
     private long permission;
     private long timemodified;
     private long modifierid;

    public MdlRoleCapabilities() {
    }

    public MdlRoleCapabilities(long contextid, long roleid, String capability, long permission, long timemodified, long modifierid) {
       this.contextid = contextid;
       this.roleid = roleid;
       this.capability = capability;
       this.permission = permission;
       this.timemodified = timemodified;
       this.modifierid = modifierid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getContextid() {
        return this.contextid;
    }
    
    public void setContextid(long contextid) {
        this.contextid = contextid;
    }
    public long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(long roleid) {
        this.roleid = roleid;
    }
    public String getCapability() {
        return this.capability;
    }
    
    public void setCapability(String capability) {
        this.capability = capability;
    }
    public long getPermission() {
        return this.permission;
    }
    
    public void setPermission(long permission) {
        this.permission = permission;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public long getModifierid() {
        return this.modifierid;
    }
    
    public void setModifierid(long modifierid) {
        this.modifierid = modifierid;
    }




}


