package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlRoleAssignments generated by hbm2java
 */
public class MdlRoleAssignments  implements java.io.Serializable {


     private Long id;
     private long roleid;
     private long contextid;
     private long userid;
     private boolean hidden;
     private long timestart;
     private long timeend;
     private long timemodified;
     private long modifierid;
     private String enrol;
     private long sortorder;

    public MdlRoleAssignments() {
    }

    public MdlRoleAssignments(long roleid, long contextid, long userid, boolean hidden, long timestart, long timeend, long timemodified, long modifierid, String enrol, long sortorder) {
       this.roleid = roleid;
       this.contextid = contextid;
       this.userid = userid;
       this.hidden = hidden;
       this.timestart = timestart;
       this.timeend = timeend;
       this.timemodified = timemodified;
       this.modifierid = modifierid;
       this.enrol = enrol;
       this.sortorder = sortorder;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(long roleid) {
        this.roleid = roleid;
    }
    public long getContextid() {
        return this.contextid;
    }
    
    public void setContextid(long contextid) {
        this.contextid = contextid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public boolean isHidden() {
        return this.hidden;
    }
    
    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }
    public long getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }
    public long getTimeend() {
        return this.timeend;
    }
    
    public void setTimeend(long timeend) {
        this.timeend = timeend;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public long getModifierid() {
        return this.modifierid;
    }
    
    public void setModifierid(long modifierid) {
        this.modifierid = modifierid;
    }
    public String getEnrol() {
        return this.enrol;
    }
    
    public void setEnrol(String enrol) {
        this.enrol = enrol;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }




}


