package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlRole generated by hbm2java
 */
public class MdlRole  implements java.io.Serializable {


     private Long id;
     private String name;
     private String shortname;
     private String description;
     private long sortorder;

    public MdlRole() {
    }

    public MdlRole(String name, String shortname, String description, long sortorder) {
       this.name = name;
       this.shortname = shortname;
       this.description = description;
       this.sortorder = sortorder;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }




}


