package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlResource generated by hbm2java
 */
public class MdlResource  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String type;
     private String reference;
     private String summary;
     private String alltext;
     private String popup;
     private String options;
     private long timemodified;

    public MdlResource() {
    }

	
    public MdlResource(long course, String name, String type, String reference, String alltext, String popup, String options, long timemodified) {
        this.course = course;
        this.name = name;
        this.type = type;
        this.reference = reference;
        this.alltext = alltext;
        this.popup = popup;
        this.options = options;
        this.timemodified = timemodified;
    }
    public MdlResource(long course, String name, String type, String reference, String summary, String alltext, String popup, String options, long timemodified) {
       this.course = course;
       this.name = name;
       this.type = type;
       this.reference = reference;
       this.summary = summary;
       this.alltext = alltext;
       this.popup = popup;
       this.options = options;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getAlltext() {
        return this.alltext;
    }
    
    public void setAlltext(String alltext) {
        this.alltext = alltext;
    }
    public String getPopup() {
        return this.popup;
    }
    
    public void setPopup(String popup) {
        this.popup = popup;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


