package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScormScoesData generated by hbm2java
 */
public class MdlScormScoesData  implements java.io.Serializable {


     private Long id;
     private long scoid;
     private String name;
     private String value;

    public MdlScormScoesData() {
    }

    public MdlScormScoesData(long scoid, String name, String value) {
       this.scoid = scoid;
       this.name = name;
       this.value = value;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getScoid() {
        return this.scoid;
    }
    
    public void setScoid(long scoid) {
        this.scoid = scoid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


