package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScormSeqRolluprule generated by hbm2java
 */
public class MdlScormSeqRolluprule  implements java.io.Serializable {


     private Long id;
     private long scoid;
     private String childactivityset;
     private long minimumcount;
     private float minimumpercent;
     private String conditioncombination;
     private String action;

    public MdlScormSeqRolluprule() {
    }

    public MdlScormSeqRolluprule(long scoid, String childactivityset, long minimumcount, float minimumpercent, String conditioncombination, String action) {
       this.scoid = scoid;
       this.childactivityset = childactivityset;
       this.minimumcount = minimumcount;
       this.minimumpercent = minimumpercent;
       this.conditioncombination = conditioncombination;
       this.action = action;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getScoid() {
        return this.scoid;
    }
    
    public void setScoid(long scoid) {
        this.scoid = scoid;
    }
    public String getChildactivityset() {
        return this.childactivityset;
    }
    
    public void setChildactivityset(String childactivityset) {
        this.childactivityset = childactivityset;
    }
    public long getMinimumcount() {
        return this.minimumcount;
    }
    
    public void setMinimumcount(long minimumcount) {
        this.minimumcount = minimumcount;
    }
    public float getMinimumpercent() {
        return this.minimumpercent;
    }
    
    public void setMinimumpercent(float minimumpercent) {
        this.minimumpercent = minimumpercent;
    }
    public String getConditioncombination() {
        return this.conditioncombination;
    }
    
    public void setConditioncombination(String conditioncombination) {
        this.conditioncombination = conditioncombination;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


