package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScormSeqRuleconds generated by hbm2java
 */
public class MdlScormSeqRuleconds  implements java.io.Serializable {


     private Long id;
     private long scoid;
     private String conditioncombination;
     private byte ruletype;
     private String action;

    public MdlScormSeqRuleconds() {
    }

    public MdlScormSeqRuleconds(long scoid, String conditioncombination, byte ruletype, String action) {
       this.scoid = scoid;
       this.conditioncombination = conditioncombination;
       this.ruletype = ruletype;
       this.action = action;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getScoid() {
        return this.scoid;
    }
    
    public void setScoid(long scoid) {
        this.scoid = scoid;
    }
    public String getConditioncombination() {
        return this.conditioncombination;
    }
    
    public void setConditioncombination(String conditioncombination) {
        this.conditioncombination = conditioncombination;
    }
    public byte getRuletype() {
        return this.ruletype;
    }
    
    public void setRuletype(byte ruletype) {
        this.ruletype = ruletype;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


