package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlSurveyAnalysis generated by hbm2java
 */
public class MdlSurveyAnalysis  implements java.io.Serializable {


     private Long id;
     private long survey;
     private long userid;
     private String notes;

    public MdlSurveyAnalysis() {
    }

    public MdlSurveyAnalysis(long survey, long userid, String notes) {
       this.survey = survey;
       this.userid = userid;
       this.notes = notes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getSurvey() {
        return this.survey;
    }
    
    public void setSurvey(long survey) {
        this.survey = survey;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


