package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlSurvey generated by hbm2java
 */
public class MdlSurvey  implements java.io.Serializable {


     private Long id;
     private long course;
     private long template;
     private int days;
     private long timecreated;
     private long timemodified;
     private String name;
     private String intro;
     private String questions;

    public MdlSurvey() {
    }

    public MdlSurvey(long course, long template, int days, long timecreated, long timemodified, String name, String intro, String questions) {
       this.course = course;
       this.template = template;
       this.days = days;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.name = name;
       this.intro = intro;
       this.questions = questions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getTemplate() {
        return this.template;
    }
    
    public void setTemplate(long template) {
        this.template = template;
    }
    public int getDays() {
        return this.days;
    }
    
    public void setDays(int days) {
        this.days = days;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public String getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(String questions) {
        this.questions = questions;
    }




}


