package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlStatsUserWeekly generated by hbm2java
 */
public class MdlStatsUserWeekly  implements java.io.Serializable {


     private Long id;
     private long courseid;
     private long userid;
     private long roleid;
     private long timeend;
     private long statsreads;
     private long statswrites;
     private String stattype;

    public MdlStatsUserWeekly() {
    }

    public MdlStatsUserWeekly(long courseid, long userid, long roleid, long timeend, long statsreads, long statswrites, String stattype) {
       this.courseid = courseid;
       this.userid = userid;
       this.roleid = roleid;
       this.timeend = timeend;
       this.statsreads = statsreads;
       this.statswrites = statswrites;
       this.stattype = stattype;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(long roleid) {
        this.roleid = roleid;
    }
    public long getTimeend() {
        return this.timeend;
    }
    
    public void setTimeend(long timeend) {
        this.timeend = timeend;
    }
    public long getStatsreads() {
        return this.statsreads;
    }
    
    public void setStatsreads(long statsreads) {
        this.statsreads = statsreads;
    }
    public long getStatswrites() {
        return this.statswrites;
    }
    
    public void setStatswrites(long statswrites) {
        this.statswrites = statswrites;
    }
    public String getStattype() {
        return this.stattype;
    }
    
    public void setStattype(String stattype) {
        this.stattype = stattype;
    }




}


