package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScormSeqRulecond generated by hbm2java
 */
public class MdlScormSeqRulecond  implements java.io.Serializable {


     private Long id;
     private long scoid;
     private long ruleconditionsid;
     private String refrencedobjective;
     private float measurethreshold;
     private String operator;
     private String cond;

    public MdlScormSeqRulecond() {
    }

    public MdlScormSeqRulecond(long scoid, long ruleconditionsid, String refrencedobjective, float measurethreshold, String operator, String cond) {
       this.scoid = scoid;
       this.ruleconditionsid = ruleconditionsid;
       this.refrencedobjective = refrencedobjective;
       this.measurethreshold = measurethreshold;
       this.operator = operator;
       this.cond = cond;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getScoid() {
        return this.scoid;
    }
    
    public void setScoid(long scoid) {
        this.scoid = scoid;
    }
    public long getRuleconditionsid() {
        return this.ruleconditionsid;
    }
    
    public void setRuleconditionsid(long ruleconditionsid) {
        this.ruleconditionsid = ruleconditionsid;
    }
    public String getRefrencedobjective() {
        return this.refrencedobjective;
    }
    
    public void setRefrencedobjective(String refrencedobjective) {
        this.refrencedobjective = refrencedobjective;
    }
    public float getMeasurethreshold() {
        return this.measurethreshold;
    }
    
    public void setMeasurethreshold(float measurethreshold) {
        this.measurethreshold = measurethreshold;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getCond() {
        return this.cond;
    }
    
    public void setCond(String cond) {
        this.cond = cond;
    }




}


