package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScorm generated by hbm2java
 */
public class MdlScorm  implements java.io.Serializable {


     private Long id;
     private String version;
     private long course;
     private String name;
     private String reference;
     private String summary;
     private double maxgrade;
     private byte grademethod;
     private long whatgrade;
     private long maxattempt;
     private boolean updatefreq;
     private String md5hash;
     private long launch;
     private boolean skipview;
     private boolean hidebrowse;
     private boolean hidetoc;
     private boolean hidenav;
     private boolean auto;
     private boolean popup;
     private String options;
     private long width;
     private long height;
     private long timemodified;

    public MdlScorm() {
    }

    public MdlScorm(long course, String name, String reference, String summary, double maxgrade, byte grademethod, long whatgrade, long maxattempt, boolean updatefreq, String md5hash, long launch, boolean skipview, boolean hidebrowse, boolean hidetoc, boolean hidenav, boolean auto, boolean popup, String options, long width, long height, long timemodified) {
       this.course = course;
       this.name = name;
       this.reference = reference;
       this.summary = summary;
       this.maxgrade = maxgrade;
       this.grademethod = grademethod;
       this.whatgrade = whatgrade;
       this.maxattempt = maxattempt;
       this.updatefreq = updatefreq;
       this.md5hash = md5hash;
       this.launch = launch;
       this.skipview = skipview;
       this.hidebrowse = hidebrowse;
       this.hidetoc = hidetoc;
       this.hidenav = hidenav;
       this.auto = auto;
       this.popup = popup;
       this.options = options;
       this.width = width;
       this.height = height;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public double getMaxgrade() {
        return this.maxgrade;
    }
    
    public void setMaxgrade(double maxgrade) {
        this.maxgrade = maxgrade;
    }
    public byte getGrademethod() {
        return this.grademethod;
    }
    
    public void setGrademethod(byte grademethod) {
        this.grademethod = grademethod;
    }
    public long getWhatgrade() {
        return this.whatgrade;
    }
    
    public void setWhatgrade(long whatgrade) {
        this.whatgrade = whatgrade;
    }
    public long getMaxattempt() {
        return this.maxattempt;
    }
    
    public void setMaxattempt(long maxattempt) {
        this.maxattempt = maxattempt;
    }
    public boolean isUpdatefreq() {
        return this.updatefreq;
    }
    
    public void setUpdatefreq(boolean updatefreq) {
        this.updatefreq = updatefreq;
    }
    public String getMd5hash() {
        return this.md5hash;
    }
    
    public void setMd5hash(String md5hash) {
        this.md5hash = md5hash;
    }
    public long getLaunch() {
        return this.launch;
    }
    
    public void setLaunch(long launch) {
        this.launch = launch;
    }
    public boolean isSkipview() {
        return this.skipview;
    }
    
    public void setSkipview(boolean skipview) {
        this.skipview = skipview;
    }
    public boolean isHidebrowse() {
        return this.hidebrowse;
    }
    
    public void setHidebrowse(boolean hidebrowse) {
        this.hidebrowse = hidebrowse;
    }
    public boolean isHidetoc() {
        return this.hidetoc;
    }
    
    public void setHidetoc(boolean hidetoc) {
        this.hidetoc = hidetoc;
    }
    public boolean isHidenav() {
        return this.hidenav;
    }
    
    public void setHidenav(boolean hidenav) {
        this.hidenav = hidenav;
    }
    public boolean isAuto() {
        return this.auto;
    }
    
    public void setAuto(boolean auto) {
        this.auto = auto;
    }
    public boolean isPopup() {
        return this.popup;
    }
    
    public void setPopup(boolean popup) {
        this.popup = popup;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }
    public long getWidth() {
        return this.width;
    }
    
    public void setWidth(long width) {
        this.width = width;
    }
    public long getHeight() {
        return this.height;
    }
    
    public void setHeight(long height) {
        this.height = height;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


