package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlSurveyAnswers generated by hbm2java
 */
public class MdlSurveyAnswers  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long survey;
     private long question;
     private long time;
     private String answer1;
     private String answer2;

    public MdlSurveyAnswers() {
    }

    public MdlSurveyAnswers(long userid, long survey, long question, long time, String answer1, String answer2) {
       this.userid = userid;
       this.survey = survey;
       this.question = question;
       this.time = time;
       this.answer1 = answer1;
       this.answer2 = answer2;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getSurvey() {
        return this.survey;
    }
    
    public void setSurvey(long survey) {
        this.survey = survey;
    }
    public long getQuestion() {
        return this.question;
    }
    
    public void setQuestion(long question) {
        this.question = question;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public String getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }
    public String getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }




}


