package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlScormSeqMapinfo generated by hbm2java
 */
public class MdlScormSeqMapinfo  implements java.io.Serializable {


     private Long id;
     private long scoid;
     private long objectiveid;
     private long targetobjectiveid;
     private boolean readsatisfiedstatus;
     private boolean readnormalizedmeasure;
     private boolean writesatisfiedstatus;
     private boolean writenormalizedmeasure;

    public MdlScormSeqMapinfo() {
    }

    public MdlScormSeqMapinfo(long scoid, long objectiveid, long targetobjectiveid, boolean readsatisfiedstatus, boolean readnormalizedmeasure, boolean writesatisfiedstatus, boolean writenormalizedmeasure) {
       this.scoid = scoid;
       this.objectiveid = objectiveid;
       this.targetobjectiveid = targetobjectiveid;
       this.readsatisfiedstatus = readsatisfiedstatus;
       this.readnormalizedmeasure = readnormalizedmeasure;
       this.writesatisfiedstatus = writesatisfiedstatus;
       this.writenormalizedmeasure = writenormalizedmeasure;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getScoid() {
        return this.scoid;
    }
    
    public void setScoid(long scoid) {
        this.scoid = scoid;
    }
    public long getObjectiveid() {
        return this.objectiveid;
    }
    
    public void setObjectiveid(long objectiveid) {
        this.objectiveid = objectiveid;
    }
    public long getTargetobjectiveid() {
        return this.targetobjectiveid;
    }
    
    public void setTargetobjectiveid(long targetobjectiveid) {
        this.targetobjectiveid = targetobjectiveid;
    }
    public boolean isReadsatisfiedstatus() {
        return this.readsatisfiedstatus;
    }
    
    public void setReadsatisfiedstatus(boolean readsatisfiedstatus) {
        this.readsatisfiedstatus = readsatisfiedstatus;
    }
    public boolean isReadnormalizedmeasure() {
        return this.readnormalizedmeasure;
    }
    
    public void setReadnormalizedmeasure(boolean readnormalizedmeasure) {
        this.readnormalizedmeasure = readnormalizedmeasure;
    }
    public boolean isWritesatisfiedstatus() {
        return this.writesatisfiedstatus;
    }
    
    public void setWritesatisfiedstatus(boolean writesatisfiedstatus) {
        this.writesatisfiedstatus = writesatisfiedstatus;
    }
    public boolean isWritenormalizedmeasure() {
        return this.writenormalizedmeasure;
    }
    
    public void setWritenormalizedmeasure(boolean writenormalizedmeasure) {
        this.writenormalizedmeasure = writenormalizedmeasure;
    }




}


