package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MdlSessions2 generated by hbm2java
 */
public class MdlSessions2  implements java.io.Serializable {


     private String sesskey;
     private Date expiry;
     private String expireref;
     private Date created;
     private Date modified;
     private String sessdata;

    public MdlSessions2() {
    }

	
    public MdlSessions2(String sesskey, Date expiry, Date created, Date modified) {
        this.sesskey = sesskey;
        this.expiry = expiry;
        this.created = created;
        this.modified = modified;
    }
    public MdlSessions2(String sesskey, Date expiry, String expireref, Date created, Date modified, String sessdata) {
       this.sesskey = sesskey;
       this.expiry = expiry;
       this.expireref = expireref;
       this.created = created;
       this.modified = modified;
       this.sessdata = sessdata;
    }
   
    public String getSesskey() {
        return this.sesskey;
    }
    
    public void setSesskey(String sesskey) {
        this.sesskey = sesskey;
    }
    public Date getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(Date expiry) {
        this.expiry = expiry;
    }
    public String getExpireref() {
        return this.expireref;
    }
    
    public void setExpireref(String expireref) {
        this.expireref = expireref;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public String getSessdata() {
        return this.sessdata;
    }
    
    public void setSessdata(String sessdata) {
        this.sessdata = sessdata;
    }




}


