package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlTagInstance generated by hbm2java
 */
public class MdlTagInstance  implements java.io.Serializable {


     private Long id;
     private long tagid;
     private String itemtype;
     private long itemid;
     private Long ordering;
     private long timemodified;

    public MdlTagInstance() {
    }

	
    public MdlTagInstance(long tagid, String itemtype, long itemid, long timemodified) {
        this.tagid = tagid;
        this.itemtype = itemtype;
        this.itemid = itemid;
        this.timemodified = timemodified;
    }
    public MdlTagInstance(long tagid, String itemtype, long itemid, Long ordering, long timemodified) {
       this.tagid = tagid;
       this.itemtype = itemtype;
       this.itemid = itemid;
       this.ordering = ordering;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getTagid() {
        return this.tagid;
    }
    
    public void setTagid(long tagid) {
        this.tagid = tagid;
    }
    public String getItemtype() {
        return this.itemtype;
    }
    
    public void setItemtype(String itemtype) {
        this.itemtype = itemtype;
    }
    public long getItemid() {
        return this.itemid;
    }
    
    public void setItemid(long itemid) {
        this.itemid = itemid;
    }
    public Long getOrdering() {
        return this.ordering;
    }
    
    public void setOrdering(Long ordering) {
        this.ordering = ordering;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


