package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlTagCorrelation generated by hbm2java
 */
public class MdlTagCorrelation  implements java.io.Serializable {


     private Long id;
     private long tagid;
     private String correlatedtags;

    public MdlTagCorrelation() {
    }

    public MdlTagCorrelation(long tagid, String correlatedtags) {
       this.tagid = tagid;
       this.correlatedtags = correlatedtags;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getTagid() {
        return this.tagid;
    }
    
    public void setTagid(long tagid) {
        this.tagid = tagid;
    }
    public String getCorrelatedtags() {
        return this.correlatedtags;
    }
    
    public void setCorrelatedtags(String correlatedtags) {
        this.correlatedtags = correlatedtags;
    }




}


