package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlTag generated by hbm2java
 */
public class MdlTag  implements java.io.Serializable {


     private Long id;
     private long userid;
     private String name;
     private String rawname;
     private String tagtype;
     private String description;
     private byte descriptionformat;
     private Short flag;
     private Long timemodified;

    public MdlTag() {
    }

	
    public MdlTag(long userid, String name, String rawname, byte descriptionformat) {
        this.userid = userid;
        this.name = name;
        this.rawname = rawname;
        this.descriptionformat = descriptionformat;
    }
    public MdlTag(long userid, String name, String rawname, String tagtype, String description, byte descriptionformat, Short flag, Long timemodified) {
       this.userid = userid;
       this.name = name;
       this.rawname = rawname;
       this.tagtype = tagtype;
       this.description = description;
       this.descriptionformat = descriptionformat;
       this.flag = flag;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRawname() {
        return this.rawname;
    }
    
    public void setRawname(String rawname) {
        this.rawname = rawname;
    }
    public String getTagtype() {
        return this.tagtype;
    }
    
    public void setTagtype(String tagtype) {
        this.tagtype = tagtype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getDescriptionformat() {
        return this.descriptionformat;
    }
    
    public void setDescriptionformat(byte descriptionformat) {
        this.descriptionformat = descriptionformat;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public Long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(Long timemodified) {
        this.timemodified = timemodified;
    }




}


