package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlUserPrivateKey generated by hbm2java
 */
public class MdlUserPrivateKey  implements java.io.Serializable {


     private Long id;
     private String script;
     private String value;
     private long userid;
     private Long instance;
     private String iprestriction;
     private Long validuntil;
     private Long timecreated;

    public MdlUserPrivateKey() {
    }

	
    public MdlUserPrivateKey(String script, String value, long userid) {
        this.script = script;
        this.value = value;
        this.userid = userid;
    }
    public MdlUserPrivateKey(String script, String value, long userid, Long instance, String iprestriction, Long validuntil, Long timecreated) {
       this.script = script;
       this.value = value;
       this.userid = userid;
       this.instance = instance;
       this.iprestriction = iprestriction;
       this.validuntil = validuntil;
       this.timecreated = timecreated;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getScript() {
        return this.script;
    }
    
    public void setScript(String script) {
        this.script = script;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public Long getInstance() {
        return this.instance;
    }
    
    public void setInstance(Long instance) {
        this.instance = instance;
    }
    public String getIprestriction() {
        return this.iprestriction;
    }
    
    public void setIprestriction(String iprestriction) {
        this.iprestriction = iprestriction;
    }
    public Long getValiduntil() {
        return this.validuntil;
    }
    
    public void setValiduntil(Long validuntil) {
        this.validuntil = validuntil;
    }
    public Long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(Long timecreated) {
        this.timecreated = timecreated;
    }




}


