package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlUserInfoData generated by hbm2java
 */
public class MdlUserInfoData  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long fieldid;
     private String data;

    public MdlUserInfoData() {
    }

    public MdlUserInfoData(long userid, long fieldid, String data) {
       this.userid = userid;
       this.fieldid = fieldid;
       this.data = data;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getFieldid() {
        return this.fieldid;
    }
    
    public void setFieldid(long fieldid) {
        this.fieldid = fieldid;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


