package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlUserLastaccess generated by hbm2java
 */
public class MdlUserLastaccess  implements java.io.Serializable {


     private Long id;
     private long userid;
     private long courseid;
     private long timeaccess;

    public MdlUserLastaccess() {
    }

    public MdlUserLastaccess(long userid, long courseid, long timeaccess) {
       this.userid = userid;
       this.courseid = courseid;
       this.timeaccess = timeaccess;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(long courseid) {
        this.courseid = courseid;
    }
    public long getTimeaccess() {
        return this.timeaccess;
    }
    
    public void setTimeaccess(long timeaccess) {
        this.timeaccess = timeaccess;
    }




}


