package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlUserInfoField generated by hbm2java
 */
public class MdlUserInfoField  implements java.io.Serializable {


     private Long id;
     private String shortname;
     private String name;
     private String datatype;
     private String description;
     private long categoryid;
     private long sortorder;
     private byte required;
     private byte locked;
     private short visible;
     private byte forceunique;
     private byte signup;
     private String defaultdata;
     private String param1;
     private String param2;
     private String param3;
     private String param4;
     private String param5;

    public MdlUserInfoField() {
    }

	
    public MdlUserInfoField(String shortname, String name, String datatype, long categoryid, long sortorder, byte required, byte locked, short visible, byte forceunique, byte signup) {
        this.shortname = shortname;
        this.name = name;
        this.datatype = datatype;
        this.categoryid = categoryid;
        this.sortorder = sortorder;
        this.required = required;
        this.locked = locked;
        this.visible = visible;
        this.forceunique = forceunique;
        this.signup = signup;
    }
    public MdlUserInfoField(String shortname, String name, String datatype, String description, long categoryid, long sortorder, byte required, byte locked, short visible, byte forceunique, byte signup, String defaultdata, String param1, String param2, String param3, String param4, String param5) {
       this.shortname = shortname;
       this.name = name;
       this.datatype = datatype;
       this.description = description;
       this.categoryid = categoryid;
       this.sortorder = sortorder;
       this.required = required;
       this.locked = locked;
       this.visible = visible;
       this.forceunique = forceunique;
       this.signup = signup;
       this.defaultdata = defaultdata;
       this.param1 = param1;
       this.param2 = param2;
       this.param3 = param3;
       this.param4 = param4;
       this.param5 = param5;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(long categoryid) {
        this.categoryid = categoryid;
    }
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }
    public byte getRequired() {
        return this.required;
    }
    
    public void setRequired(byte required) {
        this.required = required;
    }
    public byte getLocked() {
        return this.locked;
    }
    
    public void setLocked(byte locked) {
        this.locked = locked;
    }
    public short getVisible() {
        return this.visible;
    }
    
    public void setVisible(short visible) {
        this.visible = visible;
    }
    public byte getForceunique() {
        return this.forceunique;
    }
    
    public void setForceunique(byte forceunique) {
        this.forceunique = forceunique;
    }
    public byte getSignup() {
        return this.signup;
    }
    
    public void setSignup(byte signup) {
        this.signup = signup;
    }
    public String getDefaultdata() {
        return this.defaultdata;
    }
    
    public void setDefaultdata(String defaultdata) {
        this.defaultdata = defaultdata;
    }
    public String getParam1() {
        return this.param1;
    }
    
    public void setParam1(String param1) {
        this.param1 = param1;
    }
    public String getParam2() {
        return this.param2;
    }
    
    public void setParam2(String param2) {
        this.param2 = param2;
    }
    public String getParam3() {
        return this.param3;
    }
    
    public void setParam3(String param3) {
        this.param3 = param3;
    }
    public String getParam4() {
        return this.param4;
    }
    
    public void setParam4(String param4) {
        this.param4 = param4;
    }
    public String getParam5() {
        return this.param5;
    }
    
    public void setParam5(String param5) {
        this.param5 = param5;
    }




}


