package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWorkshop generated by hbm2java
 */
public class MdlWorkshop  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String description;
     private short wtype;
     private short nelements;
     private short nattachments;
     private byte phase;
     private byte format;
     private byte gradingstrategy;
     private byte resubmit;
     private byte agreeassessments;
     private byte hidegrades;
     private byte anonymous;
     private byte includeself;
     private long maxbytes;
     private long submissionstart;
     private long assessmentstart;
     private long submissionend;
     private long assessmentend;
     private long releasegrades;
     private short grade;
     private short gradinggrade;
     private short ntassessments;
     private short assessmentcomps;
     private short nsassessments;
     private short overallocation;
     private long timemodified;
     private short teacherweight;
     private short showleaguetable;
     private short usepassword;
     private String password;

    public MdlWorkshop() {
    }

    public MdlWorkshop(long course, String name, String description, short wtype, short nelements, short nattachments, byte phase, byte format, byte gradingstrategy, byte resubmit, byte agreeassessments, byte hidegrades, byte anonymous, byte includeself, long maxbytes, long submissionstart, long assessmentstart, long submissionend, long assessmentend, long releasegrades, short grade, short gradinggrade, short ntassessments, short assessmentcomps, short nsassessments, short overallocation, long timemodified, short teacherweight, short showleaguetable, short usepassword, String password) {
       this.course = course;
       this.name = name;
       this.description = description;
       this.wtype = wtype;
       this.nelements = nelements;
       this.nattachments = nattachments;
       this.phase = phase;
       this.format = format;
       this.gradingstrategy = gradingstrategy;
       this.resubmit = resubmit;
       this.agreeassessments = agreeassessments;
       this.hidegrades = hidegrades;
       this.anonymous = anonymous;
       this.includeself = includeself;
       this.maxbytes = maxbytes;
       this.submissionstart = submissionstart;
       this.assessmentstart = assessmentstart;
       this.submissionend = submissionend;
       this.assessmentend = assessmentend;
       this.releasegrades = releasegrades;
       this.grade = grade;
       this.gradinggrade = gradinggrade;
       this.ntassessments = ntassessments;
       this.assessmentcomps = assessmentcomps;
       this.nsassessments = nsassessments;
       this.overallocation = overallocation;
       this.timemodified = timemodified;
       this.teacherweight = teacherweight;
       this.showleaguetable = showleaguetable;
       this.usepassword = usepassword;
       this.password = password;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public short getWtype() {
        return this.wtype;
    }
    
    public void setWtype(short wtype) {
        this.wtype = wtype;
    }
    public short getNelements() {
        return this.nelements;
    }
    
    public void setNelements(short nelements) {
        this.nelements = nelements;
    }
    public short getNattachments() {
        return this.nattachments;
    }
    
    public void setNattachments(short nattachments) {
        this.nattachments = nattachments;
    }
    public byte getPhase() {
        return this.phase;
    }
    
    public void setPhase(byte phase) {
        this.phase = phase;
    }
    public byte getFormat() {
        return this.format;
    }
    
    public void setFormat(byte format) {
        this.format = format;
    }
    public byte getGradingstrategy() {
        return this.gradingstrategy;
    }
    
    public void setGradingstrategy(byte gradingstrategy) {
        this.gradingstrategy = gradingstrategy;
    }
    public byte getResubmit() {
        return this.resubmit;
    }
    
    public void setResubmit(byte resubmit) {
        this.resubmit = resubmit;
    }
    public byte getAgreeassessments() {
        return this.agreeassessments;
    }
    
    public void setAgreeassessments(byte agreeassessments) {
        this.agreeassessments = agreeassessments;
    }
    public byte getHidegrades() {
        return this.hidegrades;
    }
    
    public void setHidegrades(byte hidegrades) {
        this.hidegrades = hidegrades;
    }
    public byte getAnonymous() {
        return this.anonymous;
    }
    
    public void setAnonymous(byte anonymous) {
        this.anonymous = anonymous;
    }
    public byte getIncludeself() {
        return this.includeself;
    }
    
    public void setIncludeself(byte includeself) {
        this.includeself = includeself;
    }
    public long getMaxbytes() {
        return this.maxbytes;
    }
    
    public void setMaxbytes(long maxbytes) {
        this.maxbytes = maxbytes;
    }
    public long getSubmissionstart() {
        return this.submissionstart;
    }
    
    public void setSubmissionstart(long submissionstart) {
        this.submissionstart = submissionstart;
    }
    public long getAssessmentstart() {
        return this.assessmentstart;
    }
    
    public void setAssessmentstart(long assessmentstart) {
        this.assessmentstart = assessmentstart;
    }
    public long getSubmissionend() {
        return this.submissionend;
    }
    
    public void setSubmissionend(long submissionend) {
        this.submissionend = submissionend;
    }
    public long getAssessmentend() {
        return this.assessmentend;
    }
    
    public void setAssessmentend(long assessmentend) {
        this.assessmentend = assessmentend;
    }
    public long getReleasegrades() {
        return this.releasegrades;
    }
    
    public void setReleasegrades(long releasegrades) {
        this.releasegrades = releasegrades;
    }
    public short getGrade() {
        return this.grade;
    }
    
    public void setGrade(short grade) {
        this.grade = grade;
    }
    public short getGradinggrade() {
        return this.gradinggrade;
    }
    
    public void setGradinggrade(short gradinggrade) {
        this.gradinggrade = gradinggrade;
    }
    public short getNtassessments() {
        return this.ntassessments;
    }
    
    public void setNtassessments(short ntassessments) {
        this.ntassessments = ntassessments;
    }
    public short getAssessmentcomps() {
        return this.assessmentcomps;
    }
    
    public void setAssessmentcomps(short assessmentcomps) {
        this.assessmentcomps = assessmentcomps;
    }
    public short getNsassessments() {
        return this.nsassessments;
    }
    
    public void setNsassessments(short nsassessments) {
        this.nsassessments = nsassessments;
    }
    public short getOverallocation() {
        return this.overallocation;
    }
    
    public void setOverallocation(short overallocation) {
        this.overallocation = overallocation;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }
    public short getTeacherweight() {
        return this.teacherweight;
    }
    
    public void setTeacherweight(short teacherweight) {
        this.teacherweight = teacherweight;
    }
    public short getShowleaguetable() {
        return this.showleaguetable;
    }
    
    public void setShowleaguetable(short showleaguetable) {
        this.showleaguetable = showleaguetable;
    }
    public short getUsepassword() {
        return this.usepassword;
    }
    
    public void setUsepassword(short usepassword) {
        this.usepassword = usepassword;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


