package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWikiEntries generated by hbm2java
 */
public class MdlWikiEntries  implements java.io.Serializable {


     private Long id;
     private long wikiid;
     private long course;
     private long groupid;
     private long userid;
     private String pagename;
     private long timemodified;

    public MdlWikiEntries() {
    }

    public MdlWikiEntries(long wikiid, long course, long groupid, long userid, String pagename, long timemodified) {
       this.wikiid = wikiid;
       this.course = course;
       this.groupid = groupid;
       this.userid = userid;
       this.pagename = pagename;
       this.timemodified = timemodified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getWikiid() {
        return this.wikiid;
    }
    
    public void setWikiid(long wikiid) {
        this.wikiid = wikiid;
    }
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }
    public long getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(long groupid) {
        this.groupid = groupid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public String getPagename() {
        return this.pagename;
    }
    
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }




}


