package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWikiLocks generated by hbm2java
 */
public class MdlWikiLocks  implements java.io.Serializable {


     private Long id;
     private long wikiid;
     private String pagename;
     private long lockedby;
     private long lockedsince;
     private long lockedseen;

    public MdlWikiLocks() {
    }

    public MdlWikiLocks(long wikiid, String pagename, long lockedby, long lockedsince, long lockedseen) {
       this.wikiid = wikiid;
       this.pagename = pagename;
       this.lockedby = lockedby;
       this.lockedsince = lockedsince;
       this.lockedseen = lockedseen;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getWikiid() {
        return this.wikiid;
    }
    
    public void setWikiid(long wikiid) {
        this.wikiid = wikiid;
    }
    public String getPagename() {
        return this.pagename;
    }
    
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }
    public long getLockedby() {
        return this.lockedby;
    }
    
    public void setLockedby(long lockedby) {
        this.lockedby = lockedby;
    }
    public long getLockedsince() {
        return this.lockedsince;
    }
    
    public void setLockedsince(long lockedsince) {
        this.lockedsince = lockedsince;
    }
    public long getLockedseen() {
        return this.lockedseen;
    }
    
    public void setLockedseen(long lockedseen) {
        this.lockedseen = lockedseen;
    }




}


