package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWikiPages generated by hbm2java
 */
public class MdlWikiPages  implements java.io.Serializable {


     private Long id;
     private long version;
     private String pagename;
     private Long flags;
     private String content;
     private String author;
     private long userid;
     private Long created;
     private Long lastmodified;
     private String refs;
     private String meta;
     private Long hits;
     private long wiki;

    public MdlWikiPages() {
    }

	
    public MdlWikiPages(String pagename, long userid, long wiki) {
        this.pagename = pagename;
        this.userid = userid;
        this.wiki = wiki;
    }
    public MdlWikiPages(String pagename, Long flags, String content, String author, long userid, Long created, Long lastmodified, String refs, String meta, Long hits, long wiki) {
       this.pagename = pagename;
       this.flags = flags;
       this.content = content;
       this.author = author;
       this.userid = userid;
       this.created = created;
       this.lastmodified = lastmodified;
       this.refs = refs;
       this.meta = meta;
       this.hits = hits;
       this.wiki = wiki;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getPagename() {
        return this.pagename;
    }
    
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }
    public Long getFlags() {
        return this.flags;
    }
    
    public void setFlags(Long flags) {
        this.flags = flags;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public Long getCreated() {
        return this.created;
    }
    
    public void setCreated(Long created) {
        this.created = created;
    }
    public Long getLastmodified() {
        return this.lastmodified;
    }
    
    public void setLastmodified(Long lastmodified) {
        this.lastmodified = lastmodified;
    }
    public String getRefs() {
        return this.refs;
    }
    
    public void setRefs(String refs) {
        this.refs = refs;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Long getHits() {
        return this.hits;
    }
    
    public void setHits(Long hits) {
        this.hits = hits;
    }
    public long getWiki() {
        return this.wiki;
    }
    
    public void setWiki(long wiki) {
        this.wiki = wiki;
    }




}


