package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWorkshopAssessments generated by hbm2java
 */
public class MdlWorkshopAssessments  implements java.io.Serializable {


     private Long id;
     private long workshopid;
     private long submissionid;
     private long userid;
     private long timecreated;
     private long timegraded;
     private long timeagreed;
     private double grade;
     private short gradinggrade;
     private short teachergraded;
     private short mailed;
     private short resubmission;
     private short donotuse;
     private String generalcomment;
     private String teachercomment;

    public MdlWorkshopAssessments() {
    }

	
    public MdlWorkshopAssessments(long workshopid, long submissionid, long userid, long timecreated, long timegraded, long timeagreed, double grade, short gradinggrade, short teachergraded, short mailed, short resubmission, short donotuse) {
        this.workshopid = workshopid;
        this.submissionid = submissionid;
        this.userid = userid;
        this.timecreated = timecreated;
        this.timegraded = timegraded;
        this.timeagreed = timeagreed;
        this.grade = grade;
        this.gradinggrade = gradinggrade;
        this.teachergraded = teachergraded;
        this.mailed = mailed;
        this.resubmission = resubmission;
        this.donotuse = donotuse;
    }
    public MdlWorkshopAssessments(long workshopid, long submissionid, long userid, long timecreated, long timegraded, long timeagreed, double grade, short gradinggrade, short teachergraded, short mailed, short resubmission, short donotuse, String generalcomment, String teachercomment) {
       this.workshopid = workshopid;
       this.submissionid = submissionid;
       this.userid = userid;
       this.timecreated = timecreated;
       this.timegraded = timegraded;
       this.timeagreed = timeagreed;
       this.grade = grade;
       this.gradinggrade = gradinggrade;
       this.teachergraded = teachergraded;
       this.mailed = mailed;
       this.resubmission = resubmission;
       this.donotuse = donotuse;
       this.generalcomment = generalcomment;
       this.teachercomment = teachercomment;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getWorkshopid() {
        return this.workshopid;
    }
    
    public void setWorkshopid(long workshopid) {
        this.workshopid = workshopid;
    }
    public long getSubmissionid() {
        return this.submissionid;
    }
    
    public void setSubmissionid(long submissionid) {
        this.submissionid = submissionid;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }
    public long getTimegraded() {
        return this.timegraded;
    }
    
    public void setTimegraded(long timegraded) {
        this.timegraded = timegraded;
    }
    public long getTimeagreed() {
        return this.timeagreed;
    }
    
    public void setTimeagreed(long timeagreed) {
        this.timeagreed = timeagreed;
    }
    public double getGrade() {
        return this.grade;
    }
    
    public void setGrade(double grade) {
        this.grade = grade;
    }
    public short getGradinggrade() {
        return this.gradinggrade;
    }
    
    public void setGradinggrade(short gradinggrade) {
        this.gradinggrade = gradinggrade;
    }
    public short getTeachergraded() {
        return this.teachergraded;
    }
    
    public void setTeachergraded(short teachergraded) {
        this.teachergraded = teachergraded;
    }
    public short getMailed() {
        return this.mailed;
    }
    
    public void setMailed(short mailed) {
        this.mailed = mailed;
    }
    public short getResubmission() {
        return this.resubmission;
    }
    
    public void setResubmission(short resubmission) {
        this.resubmission = resubmission;
    }
    public short getDonotuse() {
        return this.donotuse;
    }
    
    public void setDonotuse(short donotuse) {
        this.donotuse = donotuse;
    }
    public String getGeneralcomment() {
        return this.generalcomment;
    }
    
    public void setGeneralcomment(String generalcomment) {
        this.generalcomment = generalcomment;
    }
    public String getTeachercomment() {
        return this.teachercomment;
    }
    
    public void setTeachercomment(String teachercomment) {
        this.teachercomment = teachercomment;
    }




}


