package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWebdavLocks generated by hbm2java
 */
public class MdlWebdavLocks  implements java.io.Serializable {


     private Long id;
     private String token;
     private String path;
     private long expiry;
     private long userid;
     private boolean recursive;
     private boolean exclusivelock;
     private long created;
     private long modified;
     private String owner;

    public MdlWebdavLocks() {
    }

	
    public MdlWebdavLocks(String token, String path, long expiry, long userid, boolean recursive, boolean exclusivelock, long created, long modified) {
        this.token = token;
        this.path = path;
        this.expiry = expiry;
        this.userid = userid;
        this.recursive = recursive;
        this.exclusivelock = exclusivelock;
        this.created = created;
        this.modified = modified;
    }
    public MdlWebdavLocks(String token, String path, long expiry, long userid, boolean recursive, boolean exclusivelock, long created, long modified, String owner) {
       this.token = token;
       this.path = path;
       this.expiry = expiry;
       this.userid = userid;
       this.recursive = recursive;
       this.exclusivelock = exclusivelock;
       this.created = created;
       this.modified = modified;
       this.owner = owner;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public long getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(long expiry) {
        this.expiry = expiry;
    }
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    public boolean isRecursive() {
        return this.recursive;
    }
    
    public void setRecursive(boolean recursive) {
        this.recursive = recursive;
    }
    public boolean isExclusivelock() {
        return this.exclusivelock;
    }
    
    public void setExclusivelock(boolean exclusivelock) {
        this.exclusivelock = exclusivelock;
    }
    public long getCreated() {
        return this.created;
    }
    
    public void setCreated(long created) {
        this.created = created;
    }
    public long getModified() {
        return this.modified;
    }
    
    public void setModified(long modified) {
        this.modified = modified;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }




}


