package alertame.moodle;
// Generated 14/07/2013 19:45:25 by Hibernate Tools 3.2.1.GA



/**
 * MdlWorkshopRubrics generated by hbm2java
 */
public class MdlWorkshopRubrics  implements java.io.Serializable {


     private Long id;
     private long workshopid;
     private long elementno;
     private short rubricno;
     private String description;

    public MdlWorkshopRubrics() {
    }

    public MdlWorkshopRubrics(long workshopid, long elementno, short rubricno, String description) {
       this.workshopid = workshopid;
       this.elementno = elementno;
       this.rubricno = rubricno;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getWorkshopid() {
        return this.workshopid;
    }
    
    public void setWorkshopid(long workshopid) {
        this.workshopid = workshopid;
    }
    public long getElementno() {
        return this.elementno;
    }
    
    public void setElementno(long elementno) {
        this.elementno = elementno;
    }
    public short getRubricno() {
        return this.rubricno;
    }
    
    public void setRubricno(short rubricno) {
        this.rubricno = rubricno;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


